# -*- coding: utf-8 -*-
"""
generate_train_gemini.py - Hand-crafted, premium Gemini 3.5 Flash dataset for train split (115 samples).
Provides natural, diverse, and contextual Vietnamese responses combined with structured XML-JSON tool calls.
"""

import json
from pathlib import Path

# Bespoke, high-quality, diverse Vietnamese responses generated by Gemini
GEMINI_TRAIN_RESPONSES = {
  "9702": '<tool_call>{"name": "play_audiobook", "arguments": {"query": "sách bởi La Quán Trung"}}</tool_call> Vâng, để tôi tìm và phát sách nói của tác giả La Quán Trung cho bạn thưởng thức ngay nhé.',
  "9671": '<tool_call>{"name": "play_audiobook", "arguments": {"title": "Tam Quốc Diễn Nghĩa", "resume": true}}</tool_call> Được chứ, tôi sẽ tiếp tục phát tác phẩm Tam Quốc Diễn Nghĩa ngay tại phần bạn đang nghe dở lần trước nhé.',
  "10249": '<tool_call>{"name": "play_game", "arguments": {"game_name": "trivia"}}</tool_call> Trò đố vui trivia đầy thú vị đây rồi! Cùng bắt đầu chơi thôi nào, bạn đã sẵn sàng chưa?',
  "3854": '<tool_call>{"name": "smart_device", "arguments": {"action": "mute", "device": "speaker"}}</tool_call> Vâng, tôi đã tắt âm lượng loa theo yêu cầu của bạn rồi.',
  "12053": '<tool_call>{"name": "recommend_movie", "arguments": {"filter": "highly_rated", "time": "this_weekend"}}</tool_call> Để tôi chọn và gợi ý cho bạn danh sách những bộ phim cực kỳ ăn khách đang chiếu vào dịp cuối tuần này nhé!',
  "15316": '<tool_call>{"name": "social_post", "arguments": {"content": "Chúc mừng gia đình có thêm thành viên mới! Chị tôi vừa sinh em bé dễ thương vô cùng!"}}</tool_call> Ôi tuyệt vời quá! Xin chúc mừng gia đình bạn nhé. Tôi đã soạn và đăng bài viết chia sẻ tin vui này lên mạng xã hội cho bạn rồi đấy.',
  "1986": '<tool_call>{"name": "smart_device", "arguments": {"action": "set_volume", "level": "medium"}}</tool_call> Dạ, tôi đã điều chỉnh âm lượng của thiết bị về mức trung bình dễ nghe rồi ạ.',
  "3948": '<tool_call>{"name": "alarm_set", "arguments": {"time": "07:00", "label": "Báo thức mới"}}</tool_call> Được chứ, bạn muốn tôi đặt báo thức vào lúc mấy giờ thế? Cho tôi biết thời gian cụ thể nhé.',
  "16274": '<tool_call>{"name": "check_email", "arguments": {"action": "refresh"}}</tool_call> Đang làm mới hộp thư của bạn... Vui lòng đợi một giây để tôi cập nhật các email mới nhất nhé.',
  "13488": '<tool_call>{"name": "search", "arguments": {"query": "dùng đường nâu thay đường trắng làm bánh quy bơ đậu phộng"}}</tool_call> Hoàn toàn được nhé bạn! Đường nâu sẽ giúp bánh quy bơ đậu phộng ẩm hơn, mềm dẻo và có mùi thơm caramel tự nhiên rất cuốn. Để tôi tra cứu chi tiết công thức thay thế cho bạn nhé.',
  "1100": 'Chào bạn! Hôm nay của bạn thế nào? Tôi cảm thấy rất tuyệt và sẵn sàng hỗ trợ bạn bất cứ việc gì đây.',
  "12175": '<tool_call>{"name": "book_taxi", "arguments": {"service": "Uber", "time": "22:00"}}</tool_call> Dạ, tôi đã đặt lịch gọi xe Uber đón bạn vào lúc 10 giờ tối nay rồi nhé. Chúc bạn có một chuyến đi an toàn!',
  "3641": '<tool_call>{"name": "smart_light", "arguments": {"action": "on", "location": "all"}}</tool_call> Vâng, tôi đã bật toàn bộ đèn trong nhà lên cho bạn rồi ạ.',
  "10246": '<tool_call>{"name": "play_game", "arguments": {"game_name": "chess"}}</tool_call> Thách đấu cờ vua sao? Rất sẵn lòng! Bạn cầm quân trắng đi trước hay muốn tôi đi nước đầu nào?',
  "12356": '<tool_call>{"name": "search", "arguments": {"query": "đặt vé tàu hỏa trực tuyến"}}</tool_call> Dạ, bạn muốn tìm vé tàu đi từ đâu đến đâu và vào ngày nào thế? Cho tôi xin thông tin để tôi tra giúp nhé.',
  "2939": '<tool_call>{"name": "play_music", "arguments": {"playlist": "recent"}}</tool_call> Đang chuẩn bị phát danh sách nhạc bạn nghe gần đây nhất. Cùng thư giãn thôi nào!',
  "2900": '<tool_call>{"name": "order_food", "arguments": {"item": "pizza pepperoni", "size": "large"}}</tool_call> Pizza Pepperoni cỡ lớn đúng không ạ? Tôi đang kết nối cửa hàng và lên đơn đặt bánh cho bạn ngay đây.',
  "5164": '<tool_call>{"name": "smart_light", "arguments": {"action": "dim", "step": 10}}</tool_call> Dạ, tôi đã điều chỉnh độ sáng giảm đi một chút cho phòng ấm cúng hơn rồi nhé.',
  "633": '<tool_call>{"name": "smart_device", "arguments": {"device": "vacuum_cleaner", "action": "start"}}</tool_call> Robot hút bụi đã khởi động và đang bắt đầu chu trình dọn dẹp nhà cửa rồi bạn nha.',
  "16193": '<tool_call>{"name": "check_email", "arguments": {"sender": "girlfriend"}}</tool_call> Để tôi kiểm tra nhanh xem bạn gái bạn có gửi thư mới nào vào hòm thư điện tử của bạn không nhé.',
  "7290": '<tool_call>{"name": "calendar_remove", "arguments": {"date": "today", "scope": "all"}}</tool_call> Vâng, tôi đã tiến hành xoá sạch toàn bộ các lịch hẹn và sự kiện đã lên lịch ngày hôm nay của bạn rồi.',
  "1155": '<tool_call>{"name": "smart_light", "arguments": {"action": "off", "location": "bedroom"}}</tool_call> Đèn phòng ngủ đã được tắt hoàn toàn. Chúc bạn có một giấc ngủ thật ngon!',
  "1339": '<tool_call>{"name": "search", "arguments": {"query": "danh sách báo thức buổi sáng"}}</tool_call> Để tôi rà soát lại hệ thống và liệt kê cho bạn các báo thức đã cài đặt vào buổi sáng nhé.',
  "10137": '<tool_call>{"name": "make_call", "arguments": {"recipient": "Mẹ"}}</tool_call> Đang kết nối cuộc gọi thoại tới Mẹ của bạn. Hãy chờ một chút nhé.',
  "12983": '<tool_call>{"name": "search", "arguments": {"query": "giá dầu thô Brent WTI hôm nay"}}</tool_call> Dạ, để tôi tra cứu nhanh bảng giá xăng dầu và giá một thùng dầu thô hôm nay cho bạn cập nhật nhé.',
  "5314": '<tool_call>{"name": "play_music", "arguments": {"action": "previous"}}</tool_call> Vâng, tôi đang mở lại bài hát bạn vừa nghe lúc nãy nhé.',
  "912": '<tool_call>{"name": "play_radio", "arguments": {"station": "Pandora favorite"}}</tool_call> Trạm phát Pandora yêu thích của bạn đã sẵn sàng. Đang bắt đầu phát nhạc đây!',
  "13565": '<tool_call>{"name": "get_currency", "arguments": {"from": "GBP", "to": "USD", "amount": 1}}</tool_call> Để tôi đối chiếu tỷ giá ngoại tệ hiện tại và quy đổi một Bảng Anh sang Đô la Mỹ cho bạn nhé.',
  "11291": '<tool_call>{"name": "play_podcast", "arguments": {"query": "most played podcast"}}</tool_call> Tôi đang tìm tập podcast được bạn phát nhiều nhất trên chương trình phát thanh để mở lên cho bạn đây.',
  "808": '<tool_call>{"name": "smart_coffee", "arguments": {"time": "08:00"}}</tool_call> Nhất trí! Tôi đã lên lịch tự động pha một tách cà phê thơm ngon vào đúng 8 giờ sáng cho bạn rồi.',
  "15772": '<tool_call>{"name": "query_contact", "arguments": {"query": "số điện thoại của anh ấy"}}</tool_call> Để tôi kiểm tra danh bạ xem số điện thoại bạn cần tìm là số nào nhé.',
  "213": '<tool_call>{"name": "get_datetime", "arguments": {"query": "hôm nay là ngày mấy"}}</tool_call> Hôm nay là thứ sáu, ngày 22 tháng 5 năm 2026 bạn nhé.',
  "12190": '<tool_call>{"name": "search", "arguments": {"query": "ga tàu hỏa gần nhất"}}</tool_call> Để tôi định vị và chỉ đường cho bạn đến ga tàu hỏa gần vị trí của bạn nhất nhé.',
  "693": '<tool_call>{"name": "track_order", "arguments": {"query": "đơn hàng thức ăn mới đặt"}}</tool_call> Dạ được, để tôi kiểm tra tình trạng giao hàng của đơn đồ ăn bạn vừa đặt xem shipper đã đi đến đâu rồi nhé.',
  "10820": '<tool_call>{"name": "list_query", "arguments": {"query": "danh sách hôm nay"}}</tool_call> Hãy để tôi mở danh sách công việc hôm nay của bạn ra để bạn kiểm tra nhé.',
  "121": '<tool_call>{"name": "search", "arguments": {"query": "truyện cười ngắn hay"}}</tool_call> Có ngay đây! Để tôi kể cho bạn nghe một câu chuyện cười cực kỳ dí dỏm để bạn xả stress nhé.',
  "12033": '<tool_call>{"name": "search", "arguments": {"query": "các cửa hàng gần đây"}}</tool_call> Đang tìm kiếm các cửa hàng mua sắm ở khu vực xung quanh bạn. Chờ tôi vài giây nhé.',
  "9679": '<tool_call>{"name": "play_audiobook", "arguments": {"query": "phát tiếp sách nói lần trước"}}</tool_call> Vâng, tôi sẽ mở lại cuốn sách nói bạn đang nghe dở dang ở lần trước để bạn nghe tiếp nhé.',
  "833": '<tool_call>{"name": "get_weather", "arguments": {"query": "tuần này có tuyết không"}}</tool_call> Để tôi cập nhật bản tin thời tiết tuần này xem ở khu vực mình có tuyết rơi không nhé.',
  "4100": '<tool_call>{"name": "get_news", "arguments": {"query": "tin tức chính trị"}}</tool_call> Tôi đang cập nhật các dòng sự kiện và tin tức chính trị nổi bật mới nhất trong ngày cho bạn đây.',
  "9911": '<tool_call>{"name": "get_recipe", "arguments": {"query": "luộc trứng trong bao lâu"}}</tool_call> Luộc trứng lòng đào hay chín hẳn thế bạn? Thông thường luộc khoảng 6 phút sẽ được trứng lòng đào cực ngon, còn 9-10 phút sẽ chín hoàn toàn. Để tôi hiển thị mẹo luộc trứng chuẩn vị nhé.',
  "1344": '<tool_call>{"name": "play_music", "arguments": {"query": "nhạc cổ điển thập niên 90"}}</tool_call> Những giai điệu cổ điển tuyệt đẹp của thập niên 90 đang được chuẩn bị để phát cho bạn. Cùng lắng nghe nào!',
  "694": '<tool_call>{"name": "track_order", "arguments": {"query": "kiểm tra đơn hàng"}}</tool_call> Để tôi kiểm tra lộ trình của tài xế giao hàng xem đơn của bạn đang di chuyển đến đâu rồi nha.',
  "787": '<tool_call>{"name": "get_weather", "arguments": {"query": "thời tiết hôm nay"}}</tool_call> Hôm nay trời khá đẹp đấy! Để tôi cung cấp chi tiết nhiệt độ và khả năng mưa hôm nay cho bạn nhé.',
  "13289": '<tool_call>{"name": "get_definition", "arguments": {"query": "vĩnh viễn"}}</tool_call> Từ "vĩnh viễn" có nghĩa là tồn tại mãi mãi, không bao giờ thay đổi hay mất đi theo thời gian bạn nhé.',
  "7961": '<tool_call>{"name": "calendar_remove", "arguments": {"query": "tất cả các cuộc họp"}}</tool_call> Dạ, tôi đã hủy và dọn dẹp sạch toàn bộ các lịch họp của bạn khỏi ứng dụng lịch rồi.',
  "5389": '<tool_call>{"name": "smart_plug", "arguments": {"action": "off", "device": "ổ cắm thông minh"}}</tool_call> Đã ngắt điện và tắt ổ cắm thông minh thành công rồi bạn nhé.',
  "8852": '<tool_call>{"name": "calendar_remove", "arguments": {"query": "công việc sắp tới"}}</tool_call> Dạ được, sự kiện công việc sắp tới trên lịch của bạn đã được xóa bỏ rồi.',
  "11048": '<tool_call>{"name": "list_query", "arguments": {"query": "tìm danh sách của tôi"}}</tool_call> Vâng, bạn muốn xem danh sách nào thế? Để tôi mở danh sách việc cần làm hoặc mua sắm ra cho bạn xem nhé.',
  "6768": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Trả tiền thuê nhà hàng tháng"}}</tool_call> Rất quan trọng! Tôi đã tạo một nhắc nhở định kỳ hàng tháng để báo bạn trả tiền thuê nhà đúng hạn rồi nhé.',
  "11983": '<tool_call>{"name": "recommend_movie", "arguments": {"genre": "romantic comedy", "location": "local cinema"}}</tool_call> Một bộ phim hài lãng mạn nhẹ nhàng sẽ rất thích hợp đấy! Để tôi tra lịch chiếu tại rạp gần bạn nhất và gợi ý nhé.',
  "3271": '<tool_call>{"name": "search", "arguments": {"query": "xóa tất cả báo thức hôm nay"}}</tool_call> Vâng, tôi đã hủy bỏ toàn bộ các báo thức được lên lịch trong ngày hôm nay của bạn rồi.',
  "35": '<tool_call>{"name": "play_music", "arguments": {"query": "phát lại bài hát vừa rồi"}}</tool_call> Bài hát tuyệt vời này xứng đáng được nghe lại! Đang phát lại bài hát đó cho bạn đây.',
  "15768": '<tool_call>{"name": "send_email", "arguments": {"recipient": "tuan@hotmail.com", "content": "gửi email đến tuấn"}}</tool_call> Tôi đã chuẩn bị xong thư gửi đến địa chỉ tuan@hotmail.com của anh Tuấn rồi. Đang tiến hành gửi đi nhé.',
  "16541": '<tool_call>{"name": "check_email", "arguments": {"sender": "Mẹ"}}</tool_call> Để tôi quét qua hòm thư điện tử và xem gần đây Mẹ có gửi cho bạn thư mới nào không nhé.',
  "6781": '<tool_call>{"name": "calendar_query", "arguments": {"query": "lịch hẹn khám bác sĩ tuần này"}}</tool_call> Để tôi kiểm tra lịch trình tuần này xem cuộc hẹn khám sức khỏe của bạn với bác sĩ được xếp vào lúc mấy giờ nhé.',
  "11008": '<tool_call>{"name": "list_query", "arguments": {"query": "việc cần hoàn thành hôm nay"}}</tool_call> Đây là danh sách các nhiệm vụ quan trọng bạn cần hoàn thành trong hôm nay. Cố gắng hoàn thành tốt nhé!',
  "12154": '<tool_call>{"name": "check_traffic", "arguments": {"location": "văn phòng"}}</tool_call> Đang kiểm tra tình trạng kẹt xe và mật độ giao thông quanh khu vực văn phòng của bạn. Đợi tôi một lát nha.',
  "11323": '<tool_call>{"name": "play_podcast", "arguments": {"query": "tập tiếp theo"}}</tool_call> Vâng, đang tải và mở tập tiếp theo của chương trình phát thanh bạn đang theo dõi đây.',
  "13082": '<tool_call>{"name": "search", "arguments": {"query": "chuyến bay đến sao hỏa năm sau"}}</tool_call> Một chuyến du hành đến hành tinh đỏ sao? Nghe thật vĩ đại! Để tôi cập nhật các dự án không gian mới nhất về các chuyến bay thử nghiệm cho bạn nhé.',
  "275": '<tool_call>{"name": "play_music", "arguments": {"action": "query", "query": "ý nghĩa bài hát Người Hãy Quên Em Đi"}}</tool_call> Bài hát "Người Hãy Quên Em Đi" của Mỹ Tâm mang giai điệu Bossanova nhẹ nhàng nhưng ẩn chứa nỗi buồn của một tình yêu tan vỡ. Để tôi tìm thêm các bài phân tích sâu sắc về tác phẩm này cho bạn nhé.',
  "34": '<tool_call>{"name": "play_music", "arguments": {"query": "Hồ Ngọc Hà"}}</tool_call> Dạ được chứ, giọng ca quyến rũ của Hồ Ngọc Hà sẽ vang lên ngay sau đây. Chúc bạn nghe nhạc vui vẻ!',
  "16307": '<tool_call>{"name": "send_email", "arguments": {"recipient": "family", "subject": "Thông báo đi ra ngoài", "content": "tạo một email cần đi ra ngoài gửi đến gia đình tôi"}}</tool_call> Vâng, tôi đã soạn xong email thông báo bạn có việc cần đi ra ngoài để gửi tới các thành viên trong gia đình bạn rồi nha.',
  "1813": '<tool_call>{"name": "smart_coffee", "arguments": {"temperature": "hot"}}</tool_call> Tuyệt vời! Máy pha cà phê thông minh đã bắt đầu chuẩn bị một ly cà phê nóng hổi, thơm lừng cho bạn đây.',
  "2827": '<tool_call>{"name": "smart_device", "arguments": {"action": "mute", "location": "living_room"}}</tool_call> Vâng, tôi đã tắt tiếng hệ thống loa tại phòng khách ngay lập tức rồi ạ.',
  "6659": 'Chào bạn! Cà phê thơm ngon của bạn đã được lên lịch pha chuẩn xác vào lúc 7 giờ sáng hôm nay rồi nha. Chúc bạn một ngày mới đầy năng lượng!',
  "1471": '<tool_call>{"name": "smart_device", "arguments": {"action": "set_volume", "level": 60}}</tool_call> Dạ, tôi đã điều chỉnh mức âm lượng loa lên mức 60 theo yêu cầu rồi ạ.',
  "129": 'Chào bạn! Hôm nay là một ngày tuyệt vời để khám phá những điều mới mẻ. Bạn có muốn nghe tôi cập nhật thời tiết, tin tức hay có dự định gì cần tôi hỗ trợ không?',
  "10452": '<tool_call>{"name": "search", "arguments": {"query": "bỏ bánh mì khỏi danh sách mua sắm"}}</tool_call> Đã xóa mặt hàng bánh mì ra khỏi danh sách mua sắm tạp hóa của bạn rồi nhé.',
  "11635": '<tool_call>{"name": "recommend_movie", "arguments": {"query": "lịch chiếu phim ngày mai"}}</tool_call> Để tôi tra cứu xem ngày mai có những bộ phim chiếu rạp hấp dẫn nào và lịch chiếu cụ thể ra sao nhé.',
  "343": '<tool_call>{"name": "get_weather", "arguments": {"query": "thời tiết ngày mai"}}</tool_call> Dự báo thời tiết ngày mai đây rồi! Để tôi xem ngày mai trời nắng hay có mưa để bạn chuẩn bị nhé.',
  "1521": '<tool_call>{"name": "smart_device", "arguments": {"action": "set_volume", "level": 10}}</tool_call> Dạ, âm lượng đã được hạ xuống mức 10 rất nhỏ gọn và êm ái rồi ạ.',
  "5572": '<tool_call>{"name": "smart_light", "arguments": {"action": "brighten", "location": "bedroom"}}</tool_call> Vâng, tôi đã tăng thêm độ sáng cho hệ thống đèn trong phòng ngủ của bạn rồi.',
  "11946": '<tool_call>{"name": "search", "arguments": {"query": "hiệu sách gần nhất"}}</tool_call> Để tôi tìm kiếm bản đồ và chỉ cho bạn lối đi ngắn nhất đến các hiệu sách ở gần khu vực của bạn nhé.',
  "12746": '<tool_call>{"name": "book_taxi", "arguments": {"service": "Uber", "pickup": "sân bay"}}</tool_call> Vâng, tôi đang mở ứng dụng Uber để đặt một chiếc xe đón bạn trực tiếp tại sảnh sân bay ngay đây ạ.',
  "13574": '<tool_call>{"name": "get_currency", "arguments": {"from": "USD", "to": "CAD"}}</tool_call> Để tôi tra cứu bảng tỷ giá hối đoái mới nhất giữa đồng Đô la Mỹ (USD) và Đô la Canada (CAD) cho bạn nhé.',
  "11765": '<tool_call>{"name": "recommend_movie", "arguments": {"query": "trò chơi học tập phim giáo dục"}}</tool_call> Để tôi gợi ý cho bạn một số chương trình và phim tài liệu vừa học vừa chơi cực kỳ bổ ích nhé.',
  "12314": '<tool_call>{"name": "search", "arguments": {"query": "lịch trình tàu Thống Nhất đến Nha Trang"}}</tool_call> Để tôi kiểm tra giờ tàu chạy và báo chính xác thời gian tàu Thống Nhất cập bến ga Nha Trang cho bạn nhé.',
  "498": '<tool_call>{"name": "smart_light", "arguments": {"action": "change_color", "color": "red"}}</tool_call> Màu đèn đã được chuyển sang màu đỏ rực rỡ theo ý thích của bạn rồi nha.',
  "6794": '<tool_call>{"name": "calendar_query", "arguments": {"query": "sự kiện lịch hôm nay"}}</tool_call> Để tôi duyệt qua thời khóa biểu hôm nay xem bạn có cuộc họp hay sự kiện quan trọng nào đã lên lịch không nhé.',
  "12495": '<tool_call>{"name": "book_taxi", "arguments": {"query": "gọi một chiếc xe"}}</tool_call> Dạ, tôi đang liên hệ dịch vụ gọi xe để điều một chiếc ô tô đến đón bạn ngay lập tức.',
  "6671": 'Chào bạn! Hôm nay trời rất đẹp, bạn có muốn tôi gợi ý một số hoạt động vui chơi giải trí hay địa điểm ăn uống thú vị quanh đây không?',
  "1255": '<tool_call>{"name": "get_news", "arguments": {"query": "tin tức cuộc bầu cử tổng thống"}}</tool_call> Tôi đang truy xuất các thông tin nóng hổi và phân tích mới nhất về diễn biến cuộc bầu cử tổng thống cho bạn đây.',
  "13311": '<tool_call>{"name": "search", "arguments": {"query": "chia ngân sách chi tiêu hàng ngày"}}</tool_call> Để tôi giúp bạn làm một phép tính nhỏ chia đều ngân sách chi tiêu hợp lý cho từng ngày trong tháng này nhé.',
  "12131": '<tool_call>{"name": "search", "arguments": {"query": "đặt vé tàu khứ hồi Vinh Hà Nội"}}</tool_call> Vâng, tôi đang truy cập hệ thống để tra cứu lịch trình và giá vé tàu hỏa khứ hồi tuyến Vinh - Hà Nội cho bạn đặt vé.',
  "7124": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Sự kiện định kỳ hàng tuần"}}</tool_call> Nhất trí! Tôi đã thiết lập một sự kiện lặp lại định kỳ vào mỗi tuần trên lịch làm việc của bạn rồi.',
  "87": '<tool_call>{"name": "order_food", "arguments": {"item": "sushi", "time": "dinner"}}</tool_call> Món sushi thơm ngon cho bữa tối đúng không ạ? Tôi đang liên hệ nhà hàng để đặt giao tận nơi cho bạn đây.',
  "9223": '<tool_call>{"name": "play_radio", "arguments": {"frequency": "98.7 FM"}}</tool_call> Dạ được, đang chuyển tần số đài phát thanh sang kênh 98.7 FM cho bạn nghe nhé.',
  "4269": 'Tôi rất vui khi biết bạn yêu thích giai điệu này! Để tôi lưu bài hát vào danh mục yêu thích và tiếp tục phát lại cho bạn thưởng thức nhé.',
  "16621": '<tool_call>{"name": "send_email", "arguments": {"recipient": "contacts", "content": "Email nhắc nhở công việc"}}</tool_call> Dạ, tôi đang tiến hành thêm các thông tin liên hệ mới vào danh bạ, đồng thời gửi email nhắc nhở công việc tới họ giúp bạn đây.',
  "395": '<tool_call>{"name": "convert_timezone", "arguments": {"from": "EST", "to": "PST"}}</tool_call> Múi giờ phương Đông (EST) nhanh hơn giờ Thái Bình Dương (PST) là 3 tiếng đồng hồ bạn nhé. Tôi đã thực hiện chuyển đổi thời gian cụ thể cho bạn rồi.',
  "949": '<tool_call>{"name": "play_music", "arguments": {"action": "skip"}}</tool_call> Tôi hiểu cảm giác của bạn! Tôi đã bỏ qua bài hát này ngay lập tức để chuyển sang bài khác hợp gu hơn rồi nhé.',
  "5056": '<tool_call>{"name": "play_music", "arguments": {"action": "query", "query": "bài hát chủ đề của Mỹ Tâm"}}</tool_call> Mỹ Tâm nổi tiếng với rất nhiều bản hit gắn liền với tên tuổi như "Ước Gì" hay "Họa Mi Tóc Nâu". Để tôi tìm và phát ngay ca khúc chủ đề đặc trưng nhất của cô ấy cho bạn nhé.',
  "1889": '<tool_call>{"name": "smart_light", "arguments": {"action": "set_mode", "mode": "disco"}}</tool_call> Sàn diễn ánh sáng đã sẵn sàng! Tôi đã chuyển hệ thống đèn sang chế độ nhấp nháy disco cực kỳ sôi động rồi nhé.',
  "214": '<tool_call>{"name": "get_datetime", "arguments": {"query": "hôm nay là ngày gì"}}</tool_call> Hôm nay là thứ sáu, ngày 22 tháng 5 năm 2026. Chúc bạn có một ngày làm việc thật hiệu quả và chuẩn bị đón cuối tuần vui vẻ!',
  "2287": '<tool_call>{"name": "smart_coffee", "arguments": {"time": "06:00"}}</tool_call> Vâng ạ, tôi đã cài đặt máy pha cà phê thông minh tự động bắt đầu hoạt động vào lúc 6h sáng để bạn có ly cà phê thơm ngon ngay khi thức dậy.',
  "10502": '<tool_call>{"name": "list_add", "arguments": {"item": ["mì ý", "sữa"], "list_name": "tạp hóa"}}</tool_call> Dạ, tôi đã ghi nhận và điền thêm mì ý cùng sữa vào danh sách mua sắm tạp hóa cho bạn rồi nha.',
  "192": '<tool_call>{"name": "smart_plug", "arguments": {"action": "on", "device": "ổ cắm"}}</tool_call> Đã cấp nguồn điện và bật ổ cắm thông minh thành công rồi bạn nhé.',
  "5880": '<tool_call>{"name": "smart_device", "arguments": {"device": "vacuum_cleaner", "action": "start"}}</tool_call> Robot dọn dẹp thông minh đã nhận lệnh và bắt đầu đi hút bụi khắp các phòng rồi ạ.',
  "4381": '<tool_call>{"name": "search", "arguments": {"query": "xóa báo thức sớm nhất ngày mai"}}</tool_call> Đã hủy bỏ thành công báo thức có giờ hẹn sớm nhất vào ngày mai của bạn rồi nhé.',
  "11985": '<tool_call>{"name": "search", "arguments": {"query": "sự kiện nổi bật cuối tuần này"}}</tool_call> Để tôi lướt qua danh sách các sự kiện văn hóa, triển lãm và hoạt động vui chơi nổi bật diễn ra vào cuối tuần này để gợi ý cho bạn nhé.',
  "14210": '<tool_call>{"name": "play_game", "arguments": {"action": "launch"}}</tool_call> Ý tưởng tuyệt vời! Đang khởi động hệ thống để bạn bắt đầu trải nghiệm thế giới trò chơi điện tử cực đỉnh nhé.',
  "492": '<tool_call>{"name": "search", "arguments": {"query": "truyện cười ngốc nghếch"}}</tool_call> Có một câu chuyện vui cực kỳ dí dỏm đây! Để tôi kể cho bạn nghe để mang lại một nụ cười sảng khoái nhé.',
  "14089": '<tool_call>{"name": "get_stock", "arguments": {"ticker": "META"}}</tool_call> Để tôi cập nhật nhanh chỉ số chứng khoán và thị giá cổ phiếu hiện tại của tập đoàn Meta (Facebook) cho bạn nhé.',
  "11893": '<tool_call>{"name": "search", "arguments": {"query": "các sự kiện cuối tuần này"}}</tool_call> Để tôi quét qua các hoạt động và sự kiện vui chơi giải trí diễn ra ở khu vực lân cận vào dịp cuối tuần này cho bạn nhé.',
  "276": '<tool_call>{"name": "play_music", "arguments": {"action": "query", "query": "ai cover bài hát Ngây Thơ"}}</tool_call> Ca khúc "Ngây Thơ" của Tăng Duy Tân có khá nhiều phiên bản cover độc đáo, nổi bật là bản kết hợp với ca sĩ Trung Quốc Huang Ling. Để tôi tìm danh sách các bản cover hay nhất cho bạn thưởng thức nhé.',
  "1075": '<tool_call>{"name": "smart_light", "arguments": {"action": "dim", "level": 20}}</tool_call> Vâng, tôi đã hạ độ sáng của đèn xuống mức 20% giúp dịu mắt hơn rồi ạ.',
  "11956": '<tool_call>{"name": "recommend_movie", "arguments": {"query": "phim đang chiếu gần tôi"}}</tool_call> Có khá nhiều bom tấn hấp dẫn đang ra rạp đấy! Để tôi hiển thị danh sách phim cùng các cụm rạp chiếu phim gần bạn nhất nhé.',
  "8695": '<tool_call>{"name": "calendar_query", "arguments": {"query": "khách mời chính của sự kiện"}}</tool_call> Để tôi truy xuất thông tin chi tiết của sự kiện trên lịch để xem vị khách mời danh dự chính là ai nhé.',
  "867": '<tool_call>{"name": "smart_plug", "arguments": {"action": "off", "device": "ổ cắm thông minh"}}</tool_call> Tôi đã thực hiện ngắt điện và tắt thiết bị ổ cắm thông minh rồi ạ.',
  "5173": '<tool_call>{"name": "alarm_set", "arguments": {"time": "07:00", "repeat": false, "snooze": false}}</tool_call> Dạ được, tôi đã đặt báo thức liên tục lúc 7 giờ sáng mai mà không bật chế độ báo lại cho bạn rồi.',
  "6084": '<tool_call>{"name": "alarm_set", "arguments": {"time": "10:00", "label": "Thức dậy"}}</tool_call> Đã đặt báo thức gọi bạn thức dậy vào đúng 10 giờ sáng rồi nhé. Chúc bạn ngủ ngon giấc!',
  "10008": '<tool_call>{"name": "get_recipe", "arguments": {"query": "cách nấu rau củ"}}</tool_call> Nấu rau củ luộc, xào hay hầm canh thế bạn? Để tôi gợi ý cho bạn một vài công thức chế biến rau củ vừa giữ trọn vitamin vừa thơm ngon đậm đà nhé.',
  "15184": '<tool_call>{"name": "social_query", "arguments": {"query": "lượt thích trạng thái hôm qua"}}</tool_call> Để tôi kiểm tra tài khoản mạng xã hội của bạn xem bài đăng trạng thái hôm qua đã nhận được bao nhiêu lượt tương tác và yêu thích nhé.',
  "8393": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Xem trận bóng rổ của con trai", "recurrence": "weekly", "day": "Friday"}}</tool_call> Dạ, tôi đã ghi nhớ và thêm lịch nhắc nhở định kỳ vào mỗi thứ sáu hàng tuần để bạn không bỏ lỡ trận bóng rổ của con trai mình rồi ạ.'
}

def main():
    # 1. Load train raw dataset to verify we have all items
    raw_path = Path(__file__).resolve().parent.parent / "dataset" / "train_raw.json"
    if not raw_path.exists():
        print(f"Error: {raw_path} does not exist.")
        return

    with open(raw_path, "r", encoding="utf-8") as f:
        raw_data = json.load(f)

    # 2. Build augmented data using Gemini's high quality hand-crafted responses
    augmented_data = []
    missing_ids = []

    for item in raw_data:
        item_id = item["id"]
        if item_id in GEMINI_TRAIN_RESPONSES:
            response = GEMINI_TRAIN_RESPONSES[item_id]
            augmented_data.append({
                "id": item_id,
                "utt": item["utt"],
                "intent": item["intent"],
                "scenario": item["scenario"],
                "response": response
            })
        else:
            missing_ids.append(item_id)

    if missing_ids:
        print(f"Warning: Missing hand-crafted responses for IDs: {missing_ids}")
    
    # 3. Save to speech_massive_lora_115_offset_0.json
    out_dir = Path(__file__).resolve().parent.parent / "dataset"
    out_dir.mkdir(exist_ok=True)
    out_path = out_dir / "speech_massive_lora_115_offset_0.json"
    
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(augmented_data, f, ensure_ascii=False, indent=2)
    
    print(f"Successfully generated {len(augmented_data)} premium Gemini responses and saved to {out_path}!")

if __name__ == "__main__":
    main()
