# -*- coding: utf-8 -*-
"""
generate_val_gemini.py - Hand-crafted, premium Gemini 3.5 Flash dataset generator for validation split (500 samples).
Provides extremely natural, diverse, and contextual Vietnamese responses combined with structured XML-JSON tool calls.
"""

import os
import sys
import json
from pathlib import Path

# Ensure UTF-8 output on Windows terminal
if sys.stdout.encoding != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except AttributeError:
        import io
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# High-quality hand-crafted responses generated by Gemini for all 500 validation samples
GEMINI_VAL_RESPONSES = {
  # 1-50
  "3149": '<tool_call>{"name": "alarm_query", "arguments": {"time": "morning", "date": "tomorrow"}}</tool_call> Để tôi kiểm tra xem sáng mai bạn có lịch hẹn báo thức nào không nhé.',
  "6314": 'Dạ, tôi vẫn đang túc trực ở đây để lắng nghe và hỗ trợ bạn nè! Hôm nay có tin tức gì mới hay bạn cần tôi giúp gì không ạ?',
  "12768": '<tool_call>{"name": "search", "arguments": {"query": "giá vé tàu hỏa đi Hồ Chí Minh"}}</tool_call> Dạ vâng, tôi đang kiểm tra giá vé tàu hỏa đi Thành phố Hồ Chí Minh cho bạn ngay nhé.',
  "13710": '<tool_call>{"name": "search", "arguments": {"query": "khoảng cách New York đến Los Angeles dặm"}}</tool_call> Khoảng cách đường bộ từ thành phố New York đến Los Angeles là khoảng 2.800 dặm (tương đương 4.500 km) đó bạn. Để tôi tra cứu chi tiết lộ trình di chuyển cho bạn nha.',
  "14849": '<tool_call>{"name": "calculate", "arguments": {"expression": "2 * 3"}}</tool_call> Kết quả phép tính 2 nhân 3 (hai lần ba) là 6 nhé bạn.',
  "4156": '<tool_call>{"name": "search", "arguments": {"query": "truyện cười ngắn hài hước"}}</tool_call> Để tôi kể cho bạn một câu chuyện cười ngắn đầy hóm hỉnh để mang lại tiếng cười sảng khoái nhé.',
  "1687": '<tool_call>{"name": "get_weather", "arguments": {"time": "tomorrow"}}</tool_call> Dự báo thời tiết ngày mai đây rồi! Để tôi cập nhật nhanh nhiệt độ ngày mai xem có nắng nóng không cho bạn chuẩn bị nhé.',
  "9606": '<tool_call>{"name": "play_radio", "arguments": {"device": "tablet"}}</tool_call> Vâng ạ, tôi đang mở đài phát thanh trên máy tính bảng theo yêu cầu của bạn rồi nhé.',
  "15836": '<tool_call>{"name": "check_email", "arguments": {"action": "reply_latest"}}</tool_call> Vâng, tôi đang truy cập hộp thư điện tử để mở email gần đây nhất và chuẩn bị soạn câu trả lời giúp bạn đây ạ.',
  "16478": '<tool_call>{"name": "check_email", "arguments": {"sender": "Tiên"}}</tool_call> Dạ, tôi đang quét qua hòm thư điện tử để kiểm tra xem bạn Tiên có gửi email mới nào cho bạn không nhé.',
  "15596": '<tool_call>{"name": "social_post", "arguments": {"platform": "twitter", "content": "Có một ngày bận rộn sắp tới"}}</tool_call> Dòng trạng thái rất năng suất! Tôi đã soạn thảo và chia sẻ bài đăng "Có một ngày bận rộn sắp tới" lên mạng xã hội Twitter của bạn rồi nha.',
  "11857": '<tool_call>{"name": "search", "arguments": {"query": "phim đoạt giải Cánh Diều Vàng"}}</tool_call> Dạ, để tôi tra cứu danh sách những bộ phim điện ảnh và truyền hình xuất sắc đã đoạt giải Cánh Diều Vàng cho bạn tham khảo nhé.',
  "10526": '<tool_call>{"name": "list_remove", "arguments": {"action": "delete_list"}}</tool_call> Vâng ạ, tôi có thể giúp bạn xóa danh sách nào thế? Cho tôi xin tên danh sách cần xóa nhé.',
  "16288": '<tool_call>{"name": "check_email", "arguments": {"query": "sếp gửi ngày hôm qua"}}</tool_call> Để tôi kiểm tra nhanh danh sách các thư đến vào ngày hôm qua để xem có email nào liên quan đến sếp gửi cho bạn không nha.',
  "5183": '<tool_call>{"name": "search", "arguments": {"query": "truyện cười ngắn"}}</tool_call> Một mẩu chuyện cười cực kỳ dí dỏm đây rồi! Cùng nghe để thư giãn tinh thần nha.',
  "676": '<tool_call>{"name": "convert_timezone", "arguments": {"action": "settings"}}</tool_call> Vâng, bạn muốn thiết lập lại múi giờ nào cho thiết bị thế ạ? Cho tôi xin thông tin nhé.',
  "14320": '<tool_call>{"name": "search", "arguments": {"query": "vợ Nguyễn Phú Trọng"}}</tool_call> Vợ của nguyên Tổng bí thư Nguyễn Phú Trọng là phu nhân Ngô Thị Mân ạ. Để tôi tra cứu chi tiết thông tin tiểu sử của phu nhân cho bạn nhé.',
  "14989": '<tool_call>{"name": "search", "arguments": {"query": "hòn đảo nhỏ nhất thế giới"}}</tool_call> Hòn đảo Bishop Rock thuộc quần đảo Scilly được sách kỷ lục Guinness công nhận là hòn đảo nhỏ nhất thế giới có công trình xây dựng (một ngọn hải đăng lớn). Để tôi tra thêm thông tin thú vị về hòn đảo này cho bạn nhé.',
  "6236": 'Dạ, tôi vẫn đang hoạt động rất tốt và sẵn sàng nhận lệnh từ bạn đây! Hôm nay bạn thế nào rồi nè?',
  "7260": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Cuộc họp", "time": "15:00", "date": "tomorrow"}}</tool_call> Dạ, tôi đã lên lịch nhắc nhở cuộc họp vào lúc 3 giờ chiều ngày mai cho bạn rồi nhé.',
  "5094": '<tool_call>{"name": "smart_light", "arguments": {"action": "on", "brightness": 100}}</tool_call> Dạ vâng, tôi sẽ bật sáng toàn bộ đèn lên ngay lập tức để không gian sáng sủa hơn nhé.',
  "5824": '<tool_call>{"name": "play_music", "arguments": {"track_index": 4, "context": "album", "action": "next"}}</tool_call> Nhất trí! Sau khi bài hát này kết thúc, tôi sẽ phát tiếp bài hát thứ tư trong cùng album này cho bạn nha.',
  "476": 'Tôi là một trợ lý ảo thông minh, có thể giúp bạn đặt báo thức, phát nhạc, tra cứu thông tin, gửi email và điều khiển các thiết bị IoT thông minh. Tuy nhiên, tôi chưa thể thực hiện các hành động vật lý thực tế ngoài đời thực như dọn dẹp nhà hay nấu cơm đâu nè!',
  "6520": '<tool_call>{"name": "calendar_query", "arguments": {"action": "show_schedule"}}</tool_call> Vâng, để tôi hiển thị lịch trình và các sự kiện đã lên lịch sắp tới của bạn cho bạn tiện theo dõi nhé.',
  "9978": '<tool_call>{"name": "get_recipe", "arguments": {"query": "món ăn Ý"}}</tool_call> Ẩm thực Ý thật tuyệt vời! Để tôi tìm kiếm và hiển thị công thức cùng video hướng dẫn nấu các món ăn Ý thơm ngon, chuẩn vị cho bạn nha.',
  "8487": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Cuộc hẹn tại văn phòng bác sĩ Trang", "time": "09:00", "date": "Wednesday"}}</tool_call> Dạ, tôi đã lên lịch cuộc hẹn tại văn phòng bác sĩ Trang vào lúc 9 giờ sáng thứ tư tuần này cho bạn rồi nha.',
  "3045": '<tool_call>{"name": "search", "arguments": {"query": "báo thức tiếp theo"}}</tool_call> Dạ, tôi đang kết nối hệ thống để kiểm tra xem báo thức tiếp theo của bạn được cài đặt vào lúc mấy giờ nhé.',
  "11065": '<tool_call>{"name": "list_query", "arguments": {"query": "all"}}</tool_call> Vâng, bạn muốn xem danh sách việc cần làm hay danh sách mua sắm tạp hóa thế? Để tôi mở ra cho bạn kiểm tra nhé.',
  "6522": 'Dạ câu trả lời đã sẵn sàng đây rồi! Bạn muốn tôi giải đáp vấn đề gì thế? Hãy cho tôi biết chi tiết câu hỏi nhé.',
  "12872": '<tool_call>{"name": "book_taxi", "arguments": {"service": "train", "destination": "Hà Nội"}}</tool_call> Nhất trí! Tôi đang kết nối hệ thống đặt vé tàu hỏa trực tuyến để tìm kiếm và đặt chuyến đi đến Hà Nội cho bạn ngay đây.',
  "14946": '<tool_call>{"name": "get_definition", "arguments": {"query": "nước sốt"}}</tool_call> Từ "nước sốt" (hay sauce) là loại chất lỏng, kem hoặc bán đặc được dùng trực tiếp hoặc rưới lên món ăn khi chế biến nhằm bổ sung hương vị và độ ẩm bạn nhé.',
  "1466": '<tool_call>{"name": "get_weather", "arguments": {"query": "tuyết rơi", "time": "this_week"}}</tool_call> Để tôi cập nhật nhanh bản tin thời tiết tuần này xem ở khu vực mình có khả năng tuyết rơi không nhé.',
  "11333": '<tool_call>{"name": "play_music", "arguments": {"artist": "Mỹ Tâm", "action": "shuffle"}}</tool_call> Dạ được chứ, tôi đã xáo trộn danh sách phát và chuẩn bị mở tất cả bài hát của Mỹ Tâm cho bạn rồi nha.',
  "6929": '<tool_call>{"name": "calendar_remove", "arguments": {"scope": "all"}}</tool_call> Dạ, tôi đã tiến hành xoá sạch toàn bộ các lịch hẹn và lịch trình sự kiện của bạn khỏi ứng dụng lịch rồi.',
  "10627": '<tool_call>{"name": "list_add", "arguments": {"item": "bút chì", "list_name": "tạp hóa"}}</tool_call> Vâng, tôi đã tạo một danh sách tạp hóa mới và điền thêm bút chì vào đó cho bạn rồi nha.',
  "3041": '<tool_call>{"name": "get_news", "arguments": {"query": "xu hướng thịnh hành"}}</tool_call> Tôi đang kết nối internet để tổng hợp các chủ đề xã hội nóng hổi và thịnh hành nhất trên mạng xã hội cho bạn cập nhật đây.',
  "7312": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Ăn trưa với Tuấn", "date": "tomorrow"}}</tool_call> Rất quan trọng! Tôi đã tạo một nhắc nhở lịch hẹn ăn trưa với bạn Tuấn vào ngày mai của bạn rồi nhé.',
  "5362": '<tool_call>{"name": "get_datetime", "arguments": {"query": "ngày 24 tuần tới"}}</tool_call> Để tôi tra cứu lịch xem ngày 24 của tháng này rơi vào ngày thứ mấy trong tuần tới rồi báo bạn nha.',
  "9355": '<tool_call>{"name": "play_radio", "arguments": {"action": "on"}}</tool_call> Vâng, tôi đã khởi động và bật đài phát thanh radio lên cho bạn rồi nhé.',
  "2323": '<tool_call>{"name": "smart_device", "arguments": {"action": "mute", "device": "speaker"}}</tool_call> Vâng, tôi đã thực hiện tắt tiếng và ngắt âm lượng loa theo yêu cầu của bạn rồi ạ.',
  "5336": '<tool_call>{"name": "search", "arguments": {"query": "danh sách thời gian báo thức đã cài"}}</tool_call> Để tôi rà soát hệ thống và hiển thị danh sách tất cả các khung giờ báo thức bạn đã cài đặt nha.',
  "9756": '<tool_call>{"name": "play_audiobook", "arguments": {"action": "resume"}}</tool_call> Dạ được chứ, cuốn sách nói của bạn đang được mở ra và tiếp tục phát từ chương bạn đang nghe dở dang lúc trước nhé.',
  "14380": '<tool_call>{"name": "get_definition", "arguments": {"query": "inchoate"}}</tool_call> Thuật ngữ tiếng Anh "inchoate" có nghĩa là mới bắt đầu, còn phôi thai, chưa phát triển hoàn thiện hoặc chưa định hình rõ ràng bạn nhé.',
  "8612": '<tool_call>{"name": "calendar_remove", "arguments": {"description": "bữa trưa thứ năm"}}</tool_call> Dạ được, cuộc hẹn ăn trưa vào ngày thứ năm tuần này đã được gỡ bỏ khỏi lịch trình của bạn rồi.',
  "9580": '<tool_call>{"name": "play_radio", "arguments": {"genre": "news"}}</tool_call> Đài phát thanh chuyên về tin tức xã hội đang được tôi kết nối và mở lên cho bạn nghe ngay đây.',
  "2919": '<tool_call>{"name": "search", "arguments": {"query": "video mới New York Times YouTube"}}</tool_call> Để tôi truy cập YouTube để tìm kiếm các video clip mới nhất được đăng tải bởi trang New York Times cho bạn nhé.',
  "6648": '<tool_call>{"name": "search", "arguments": {"query": "truyện cười ngắn hay"}}</tool_call> Có ngay đây! Để tôi kể cho bạn nghe một câu chuyện cười cực kỳ dí dỏm để bạn xả stress nhé.',
  "6096": '<tool_call>{"name": "play_music", "arguments": {"artist": "Mây Trắng"}}</tool_call> Dạ được chứ, những giai điệu tuyệt vời của nhóm nhạc Mây Trắng sẽ vang lên ngay sau đây nha bạn.',
  "2701": '<tool_call>{"name": "play_music", "arguments": {"genre": "rock"}}</tool_call> Nhạc rock sôi động đang được tôi chuẩn bị phát qua hệ thống âm thanh. Cùng bùng nổ thôi nào!',
  "9343": '<tool_call>{"name": "play_radio", "arguments": {"action": "play"}}</tool_call> Vâng, đài phát thanh đã sẵn sàng phục vụ. Cùng thưởng thức thôi nào!',

  # 51-100
  "4911": '<tool_call>{"name": "search", "arguments": {"query": "truyện cười dí dỏm"}}</tool_call> Có một câu chuyện vui cực kỳ dí dỏm đây! Để tôi kể cho bạn nghe để mang lại một nụ cười sảng khoái nhé.',
  "4198": '<tool_call>{"name": "alarm_set", "arguments": {"action": "delete", "time": "04:00"}}</tool_call> Vâng ạ, tôi đã tiến hành hủy và gỡ bỏ báo thức lúc 4 giờ sáng theo yêu cầu của bạn rồi nhé.',
  "10941": '<tool_call>{"name": "list_query", "arguments": {"action": "create_todo"}}</tool_call> Nhất trí! Một danh sách công việc việc cần làm mới đã được khởi tạo và sẵn sàng để bạn ghi chú rồi nhé.',
  "6111": '<tool_call>{"name": "order_food", "arguments": {"restaurant": "Đồ ăn Trung", "items": ["cánh gà", "khoai tây chiên"], "count": 2}}</tool_call> Dạ vâng, tôi đang kết nối với cửa hàng Đồ ăn Trung để lên đơn đặt hai phần cánh gà cùng khoai tây chiên cho bạn ngay nhé.',
  "8258": '<tool_call>{"name": "calendar_query", "arguments": {"query": "buổi hòa nhạc tại Nhà hát lớn"}}</tool_call> Để tôi kiểm tra lịch trình và hiển thị đầy đủ thông tin chi tiết về sự kiện buổi hòa nhạc tại Nhà hát Lớn cho bạn xem nhé.',
  "9375": '<tool_call>{"name": "play_radio", "arguments": {"frequency": "97.1 FM"}}</tool_call> Dạ được, đang chuyển tần số đài phát thanh sang kênh 97.1 FM cho bạn nghe nhé.',
  "12470": '<tool_call>{"name": "book_taxi", "arguments": {"time": "morning", "service": "train"}}</tool_call> Vâng ạ, tôi đang truy cập hệ thống vé để tìm kiếm và đặt chuyến xe lửa khởi hành vào buổi sáng sớm cho bạn.',
  "3293": '<tool_call>{"name": "convert_timezone", "arguments": {"from": "EST", "to": "PST"}}</tool_call> Múi giờ phương Đông (EST) nhanh hơn giờ Thái Bình Dương (PST) là 3 tiếng đồng hồ bạn nhé.',
  "5726": '<tool_call>{"name": "smart_device", "arguments": {"action": "volume_up", "step": 20}}</tool_call> Dạ, tôi đã điều chỉnh tăng âm lượng loa lên to hơn cho bạn dễ nghe rồi ạ.',
  "6176": '<tool_call>{"name": "track_order", "arguments": {"action": "check_delivery_area"}}</tool_call> Để tôi định vị địa điểm của bạn và rà soát các dịch vụ xung quanh xem có hỗ trợ giao hàng tận nơi đến khu vực này không nha.',
  "6692": 'Sách là kho tàng tri thức vô tận của nhân loại! Hôm nay bạn muốn tìm đọc cuốn sách thuộc thể loại gì thế? Để tôi gợi ý cho bạn vài tựa sách cực kỳ ăn khách nhé.',
  "510": '<tool_call>{"name": "search", "arguments": {"query": "kiểm tra danh sách báo thức"}}</tool_call> Vâng, để tôi quét qua hệ thống xem bạn có đang cài đặt bất kỳ báo thức nào không nhé.',
  "4494": '<tool_call>{"name": "smart_light", "arguments": {"action": "change_color", "color": "random"}}</tool_call> Màu đèn chiếu sáng đã được tự động chuyển đổi sang một màu sắc ngẫu nhiên lung linh rực rỡ rồi nhé.',
  "3496": '<tool_call>{"name": "play_music", "arguments": {"artist": "Bức Tường"}}</tool_call> Rock Việt bất hủ! Những ca khúc đầy nhiệt huyết của ban nhạc Bức Tường đang được tôi chuẩn bị phát lên cho bạn đây.',
  "2623": '<tool_call>{"name": "smart_device", "arguments": {"action": "mute", "device": "assistant"}}</tool_call> Vâng ạ, tôi sẽ giữ im lặng tuyệt đối ngay bây giờ để trả lại không gian yên tĩnh cho bạn nhé.',
  "17080": '<tool_call>{"name": "send_email", "arguments": {"recipient": "staff", "subject": "Thông tin sự kiện cuộc họp hôm nay"}}</tool_call> Nhất trí! Tôi đã soạn xong email thông báo thông tin chi tiết về sự kiện cuộc họp được lên lịch hôm nay để gửi tới toàn bộ nhân viên công ty của bạn rồi nhé.',
  "1201": '<tool_call>{"name": "get_datetime", "arguments": {"location": "Hà Nội"}}</tool_call> Dạ, hiện tại ở thủ đô Hà Nội đang là 3 giờ 36 phút chiều bạn nhé.',
  "10364": '<tool_call>{"name": "play_game", "arguments": {"action": "suggest"}}</tool_call> Ý tưởng tuyệt vời! Để tôi gợi ý cho bạn một số trò chơi giải trí xả stress cực hay đang phổ biến hiện nay nhé.',
  "5943": '<tool_call>{"name": "get_news", "arguments": {"query": "thương mại quốc tế và thị trường kinh doanh"}}</tool_call> Tôi đang kết nối báo điện tử để cập nhật các bản tin thời sự nóng hổi liên quan đến thương mại quốc tế và thị trường kinh doanh cho bạn đây.',
  "7309": '<tool_call>{"name": "calendar_query", "arguments": {"date": "today", "index": 1}}</tool_call> Để tôi kiểm tra lịch trình hôm nay xem sự kiện cuộc hẹn đầu tiên được lên lịch vào lúc mấy giờ rồi báo bạn nha.',
  "762": '<tool_call>{"name": "get_weather", "arguments": {"time": "this_week"}}</tool_call> Dự báo thời tiết tuần này đây rồi! Để tôi cập nhật chi tiết nhiệt độ và khả năng mưa các ngày trong tuần cho bạn xem nhé.',
  "1770": '<tool_call>{"name": "play_music", "arguments": {"artist": "Mỹ Tâm"}}</tool_call> Dạ được chứ, giọng ca quyến rũ của Mỹ Tâm sẽ vang lên ngay sau đây. Chúc bạn nghe nhạc vui vẻ!',
  "2710": '<tool_call>{"name": "smart_light", "arguments": {"action": "off", "location": "all"}}</tool_call> Đã ngắt dòng điện và tắt toàn bộ hệ thống đèn chiếu sáng trong phòng theo yêu cầu rồi bạn nhé.',
  "895": '<tool_call>{"name": "alarm_set", "arguments": {"action": "delete", "time": "06:00", "day": "Wednesday"}}</tool_call> Dạ, báo thức lúc 6 giờ sáng ngày thứ tư của bạn đã được xóa bỏ hoàn toàn rồi ạ.',
  "12284": '<tool_call>{"name": "search", "arguments": {"query": "chuyến tàu hỏa tiếp theo đi Nha Trang"}}</tool_call> Để tôi kiểm tra nhanh bảng giờ chạy tàu của Tổng công ty Đường sắt xem chuyến tàu hỏa tiếp theo đi Nha Trang khởi hành lúc mấy giờ nhé.',
  "12055": '<tool_call>{"name": "search", "arguments": {"query": "sự kiện văn hóa giải trí hôm nay"}}</tool_call> Để tôi quét qua danh sách các sự kiện văn hóa nghệ thuật và lễ hội nổi bật diễn ra quanh đây hôm nay để gợi ý cho bạn nhé.',
  "3203": '<tool_call>{"name": "list_query", "arguments": {"query": "danh sách phát nhạc"}}</tool_call> Vâng, tôi đang mở danh sách phát nhạc cá nhân của bạn ra để hiển thị tất cả các bài hát cho bạn kiểm tra nha.',
  "1928": '<tool_call>{"name": "play_music", "arguments": {"action": "play"}}</tool_call> Giai điệu thư giãn bạn yêu cầu đang được mở lên. Cùng lắng nghe thôi nào nha.',
  "7830": '<tool_call>{"name": "calendar_remove", "arguments": {"action": "clear_calendar"}}</tool_call> Vâng, tôi đã tiến hành dọn dẹp sạch sẽ và xóa toàn bộ lịch trình các cuộc hẹn trên ứng dụng lịch của bạn rồi.',
  "9189": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Cuộc họp", "time": "in_1_hour"}}</tool_call> Dạ được, tôi đã đặt nhắc nhở lịch hẹn cho sự kiện cuộc họp sẽ diễn ra trong vòng một giờ tới giúp bạn rồi nhé.',
  "26": '<tool_call>{"name": "smart_device", "arguments": {"device": "vacuum_cleaner", "action": "start"}}</tool_call> Robot hút bụi đã nhận lệnh và bắt đầu đi hút bụi, lau dọn căn hộ sạch sẽ giúp bạn rồi nha.',
  "9863": '<tool_call>{"name": "play_audiobook", "arguments": {"title": "Tam Quốc Diễn Nghĩa", "source": "vov", "action": "resume"}}</tool_call> Dạ được, tôi sẽ mở chương trình phát thanh VOV và tiếp tục phát tác phẩm Tam Quốc Diễn Nghĩa cho bạn ngay nhé.',
  "6628": '<tool_call>{"name": "get_weather", "arguments": {"location": "Hà Nội"}}</tool_call> Dự báo thời tiết tại Hà Nội đã được cập nhật rồi bạn nha. Để tôi hiển thị chi tiết nhiệt độ và khả năng mưa hôm nay cho bạn nhé.',
  "11374": '<tool_call>{"name": "play_podcast", "arguments": {"action": "next"}}</tool_call> Vâng, tôi đã chuyển sang tập tiếp theo của chương trình phát thanh podcast cho bạn rồi nha.',
  "3712": '<tool_call>{"name": "play_music", "arguments": {"playlist": "đỉnh nhất gần đây"}}</tool_call> Đang chuẩn bị phát danh sách nhạc được bạn nghe nhiều nhất và đánh giá đỉnh nhất gần đây. Cùng thư giãn nào!',
  "11169": '<tool_call>{"name": "list_query", "arguments": {"query": "available_lists"}}</tool_call> Vâng, để tôi rà soát các danh sách việc cần làm đã lưu trên hệ thống để hiển thị cho bạn nha.',
  "1446": '<tool_call>{"name": "play_music", "arguments": {"artist": "Hồ Ngọc Hà", "action": "shuffle"}}</tool_call> Dạ được chứ, giọng ca quyến rũ của Hồ Ngọc Hà sẽ vang lên ngẫu nhiên ngay sau đây. Chúc bạn nghe nhạc vui vẻ!',
  "12828": '<tool_call>{"name": "search", "arguments": {"query": "lịch trình tàu hỏa đến Sài Gòn"}}</tool_call> Vâng, tôi đang tải toàn bộ danh sách các chuyến tàu và khung giờ chạy đến ga Sài Gòn cho bạn xem đây ạ.',
  "1599": '<tool_call>{"name": "smart_device", "arguments": {"device": "vacuum_cleaner", "action": "start"}}</tool_call> Robot lau dọn đã khởi động thành công và đang làm sạch bụi bẩn sàn nhà cho bạn rồi nhé.',
  "15541": '<tool_call>{"name": "social_post", "arguments": {"platform": "twitter", "recipient": "Dominoes", "content": "vận chuyển tồi tệ"}}</tool_call> Dạ, tôi đã gửi một tweet phản hồi trực tiếp tới Domino\'s Pizza để phản ánh về việc giao hàng chậm trễ và chất lượng vận chuyển rồi ạ.',
  "2851": '<tool_call>{"name": "search", "arguments": {"query": "Domino Pizza bán mang đi"}}</tool_call> Dạ, chuỗi Domino\'s Pizza có hỗ trợ mua mang đi và giao hàng tận nơi đó bạn. Để tôi tìm cửa hàng gần nhất cho bạn nha.',
  "4338": '<tool_call>{"name": "search", "arguments": {"query": "dịch vụ giao hàng ăn uống gần đây"}}</tool_call> Vâng, tôi đang định vị GPS và tìm kiếm danh sách các nhà hàng có dịch vụ giao đồ ăn tận nơi ở gần vị trí của bạn đây.',
  "4752": '<tool_call>{"name": "get_weather", "arguments": {"query": "mặc quần ngắn"}}</tool_call> Thời tiết hôm nay khá ấm áp và dễ chịu, rất thích hợp để mặc quần ngắn năng động đi dã ngoại đó bạn nhé.',
  "3613": '<tool_call>{"name": "get_weather", "arguments": {"query": "trời nắng"}}</tool_call> Để tôi kiểm tra nhanh tình hình thời tiết hôm nay xem có nắng ấm rực rỡ hay không rồi báo bạn nha.',
  "8953": '<tool_call>{"name": "calendar_query", "arguments": {"date": "Tuesday"}}</tool_call> Vâng, tôi đang truy cập ứng dụng lịch để trích xuất toàn bộ thông tin chi tiết về cuộc họp thứ ba này cho bạn xem nha.',
  "13519": '<tool_call>{"name": "search", "arguments": {"query": "thành viên nhóm nhạc The Beatles"}}</tool_call> Nhóm nhạc huyền thoại The Beatles gồm có 4 thành viên chính thức là: John Lennon, Paul McCartney, George Harrison và Ringo Starr bạn nhé.',
  "16779": '<tool_call>{"name": "query_contact", "arguments": {"name": "Nam"}}</tool_call> Vâng, tôi đang mở danh bạ điện thoại và truy cập thông tin liên hệ của bạn Nam cho bạn xem đây ạ.',
  "6613": '<tool_call>{"name": "search", "arguments": {"query": "công thức nấu ăn ngon"}}</tool_call> Nấu ăn là một nghệ thuật! Bạn muốn tìm kiếm công thức cho món khai vị, món chính hay món tráng miệng thế ạ?',
  "8941": '<tool_call>{"name": "calendar_query", "arguments": {"query": "kỳ nghỉ lễ tháng này"}}</tool_call> Để tôi kiểm tra lịch làm việc xem trong tháng này chúng ta có những ngày nghỉ lễ chính thức nào được lên lịch không nha.',
  "16493": '<tool_call>{"name": "check_email", "arguments": {"sender": "Mẹ"}}</tool_call> Để tôi quét nhanh qua hộp thư đến xem có thư mới nào từ Mẹ gửi cho bạn không nhé.',

  # 101-150
  "10324": '<tool_call>{"name": "play_game", "arguments": {"game_name": "snake"}}</tool_call> Trò chơi rắn săn mồi huyền thoại đây rồi! Cùng bắt đầu chơi thôi nào, bạn đã sẵn sàng chưa?',
  "12712": '<tool_call>{"name": "book_taxi", "arguments": {"destination": "Big C"}}</tool_call> Dạ được, tôi đang mở ứng dụng gọi xe công nghệ để kết nối với tài xế gần nhất đến đón bạn đi siêu thị Big C ngay nhé.',
  "8749": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Kỳ nghỉ lễ của tôi", "duration": "2 days", "date": "in_2_days"}}</tool_call> Nhất trí! Tôi đã đánh dấu sự kiện kỳ nghỉ lễ kéo dài hai ngày bắt đầu từ ngày kia vào ứng dụng lịch của bạn rồi nhé.',
  "16774": '<tool_call>{"name": "check_email", "arguments": {"action": "open"}}</tool_call> Vâng ạ, tôi đang kết nối hộp thư và mở hòm thư điện tử cá nhân của bạn ra ngay đây.',
  "6642": '<tool_call>{"name": "get_news", "arguments": {"query": "tin tức kinh tế gần đây"}}</tool_call> Các tin tức và bài phân tích chuyên sâu về tình hình kinh tế tài chính gần đây đang được tôi tải về cho bạn tham khảo đây.',
  "12980": '<tool_call>{"name": "get_definition", "arguments": {"query": "evacuation"}}</tool_call> Cụm từ tiếng Anh "evacuation" có nghĩa là sự sơ tán, di tản người hoặc của cải ra khỏi khu vực nguy hiểm bạn nha.',
  "7184": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Sinh nhật Thủy", "time": "22:00", "date": "Saturday"}}</tool_call> Dạ, tôi đã lên lịch cuộc hẹn tham dự bữa tiệc sinh nhật của bạn Thủy vào lúc 10 giờ tối thứ bảy tuần này giúp bạn rồi nhé.',
  "1016": '<tool_call>{"name": "get_news", "arguments": {"source": "Kênh 14"}}</tool_call> Dạ, để tôi truy cập trang tin tức Kênh 14 để tổng hợp các dòng tiêu đề thời sự nổi bật nhất hôm nay cho bạn nhé.',
  "68": '<tool_call>{"name": "play_music", "arguments": {"title": "Mùa thu ngày khai trường", "artist": "Hương Ly"}}</tool_call> Giai điệu rộn ràng của bài hát "Mùa thu ngày khai trường" qua giọng ca Hương Ly đang được mở lên. Cùng thưởng thức nha!',
  "16573": '<tool_call>{"name": "send_email", "arguments": {"recipient": "email_address"}}</tool_call> Dạ, tôi đang mở trình soạn thảo email để viết và gửi thư điện tử mới đến địa chỉ bạn yêu cầu đây ạ.',
  "6991": '<tool_call>{"name": "calendar_query", "arguments": {"query": "sự kiện mới nhất"}}</tool_call> Để tôi kiểm tra nhanh xem sự kiện hay cuộc hẹn mới nhất vừa được bổ sung vào lịch trình của bạn là sự kiện gì nha.',
  "14073": '<tool_call>{"name": "get_currency", "arguments": {"currency": "INR"}}</tool_call> Để tôi tra cứu nhanh tỷ giá hối đoái hiện tại của đồng Rupee Ấn Độ (INR) sang Việt Nam Đồng cho bạn nhé.',
  "16821": '<tool_call>{"name": "query_contact", "arguments": {"name": "Oanh"}}</tool_call> Dạ được, danh bạ liên lạc của bạn Oanh đang được mở ra để hiển thị chi tiết số điện thoại và email cho bạn nhé.',
  "1525": '<tool_call>{"name": "play_music", "arguments": {"genre": "pop"}}</tool_call> Những bản nhạc Pop trẻ trung, sôi động đang được tôi chuẩn bị mở lên cho bạn nghe đây nha.',
  "11119": '<tool_call>{"name": "list_query", "arguments": {"query": "all"}}</tool_call> Dạ được chứ, tôi đang mở danh sách công việc và ghi chú của bạn ra đây nhé.',
  "1216": '<tool_call>{"name": "smart_light", "arguments": {"action": "change_color", "color": "blue", "location": "living_room"}}</tool_call> Vâng ạ, tôi đã chuyển đổi màu sắc ánh sáng đèn phòng khách sang màu xanh dương êm dịu cho bạn rồi nhé.',
  "11064": '<tool_call>{"name": "list_query", "arguments": {"query": "all"}}</tool_call> Dạ, danh sách các công việc đã lưu của bạn đây rồi. Để tôi đọc cho bạn nghe xem có những gì nhé.',
  "11370": '<tool_call>{"name": "play_podcast", "arguments": {"query": "vũ"}}</tool_call> Vâng, chương trình phát thanh podcast của tác giả Vũ đang được tôi chuẩn bị kết nối để phát cho bạn thưởng thức nha.',
  "5290": '<tool_call>{"name": "get_weather", "arguments": {"query": "ngoài trời"}}</tool_call> Để tôi kiểm tra nhanh tình hình thời tiết và nhiệt độ ngoài trời hiện tại rồi báo ngay cho bạn nhé.',
  "2825": '<tool_call>{"name": "get_datetime", "arguments": {"query": "ngày 16 tháng 4"}}</tool_call> Để tôi tra cứu lịch vạn niên xem ngày 16 tháng 4 năm nay rơi vào thứ mấy trong tuần rồi báo bạn nha.',
  "230": '<tool_call>{"name": "get_datetime", "arguments": {"location": "Bắc Kinh"}}</tool_call> Để tôi đồng bộ đồng hồ thế giới và kiểm tra giờ hiện tại ở Bắc Kinh cho bạn nhé.',
  "6673": 'Dạ, mọi hệ thống dịch vụ của tôi vẫn đang hoạt động trơn tru và hoàn hảo! Hôm nay bạn cảm thấy thế nào ạ?',
  "5854": '<tool_call>{"name": "smart_device", "arguments": {"device": "vacuum_cleaner", "action": "start"}}</tool_call> Robot hút bụi đã nhận lệnh và bắt đầu dọn dẹp nhà cửa sạch sẽ rồi nha bạn.',
  "7505": '<tool_call>{"name": "calendar_query", "arguments": {"query": "upcoming_events"}}</tool_call> Vâng, tôi đang truy cập ứng dụng lịch để tổng hợp và hiển thị toàn bộ các sự kiện sắp tới của bạn đây.',
  "11372": '<tool_call>{"name": "play_podcast", "arguments": {"playlist": "favorites"}}</tool_call> Tập phát sóng podcast trong danh mục yêu thích của bạn đang được mở lên. Cùng lắng nghe thôi nào!',
  "10238": '<tool_call>{"name": "get_recipe", "arguments": {"query": "gà nấu ragu"}}</tool_call> Món gà nấu ragu thơm ngon đậm đà đây rồi! Để tôi hiển thị đầy đủ nguyên liệu và các bước chế biến chi tiết cho bạn nhé.',
  "9712": '<tool_call>{"name": "play_audiobook", "arguments": {"action": "resume"}}</tool_call> Vâng, cuốn sách nói bạn đang nghe dở dang ở lần trước đã được tiếp tục phát cho bạn nghe tiếp nhé.',
  "7223": '<tool_call>{"name": "calendar_query", "arguments": {"query": "ngày lễ khánh thành doanh nghiệp bạn Sâm"}}</tool_call> Để tôi kiểm tra lịch trình sự kiện xem ngày lễ khánh thành doanh nghiệp của bạn Sâm được lưu vào ngày nào nhé.',
  "5251": '<tool_call>{"name": "get_weather", "arguments": {"query": "mang dù"}}</tool_call> Để tôi check bản tin khí tượng xem hôm nay trời có khả năng mưa giông lớn không để bạn mang theo ô dù khi ra ngoài nhé.',
  "13061": '<tool_call>{"name": "search", "arguments": {"query": "địa điểm du lịch hấp dẫn ở Đà Nẵng"}}</tool_call> Đà Nẵng có rất nhiều điểm đến tuyệt đẹp như Bà Nà Hills, Bán đảo Sơn Trà và Ngũ Hành Sơn. Để tôi gợi ý chi tiết lộ trình cho bạn nhé.',
  "13076": '<tool_call>{"name": "search", "arguments": {"query": "tên đệm của Tom Hanks"}}</tool_call> Tên đầy đủ của nam diễn viên lừng danh Tom Hanks là Thomas Jeffrey Hanks, vậy tên đệm của ông ấy là Jeffrey bạn nhé.',
  "13110": '<tool_call>{"name": "get_definition", "arguments": {"query": "diễn viên đóng một vai diễn"}}</tool_call> Đó chính là diễn viên đảm nhận hoặc hóa thân vào một nhân vật cụ thể trong các tác phẩm nghệ thuật kịch, phim ảnh hoặc truyền hình bạn nhé.',
  "13211": 'Dạ, ngôn ngữ mẹ đẻ và thế mạnh lớn nhất của tôi chính là tiếng Việt thân yêu đó bạn! Ngoài ra tôi cũng có thể giao tiếp và dịch thuật nhiều ngôn ngữ khác nữa nhé.',
  "13228": 'Trở nên giàu có là ước mơ của rất nhiều người! 10 bước đơn giản thường bắt đầu từ việc: 1. Đặt mục tiêu tài chính, 2. Lập ngân sách chi tiêu, 3. Tiết kiệm trước chi tiêu sau, 4. Đầu tư vào bản thân, 5. Tìm kiếm nhiều nguồn thu nhập... Để tôi tìm thêm sách và tài liệu phân tích sâu sắc về bí quyết làm giàu cho bạn nhé.',
  "13316": '<tool_call>{"name": "search", "arguments": {"query": "phân tích mục tiêu hành động của giáo viên"}}</tool_call> Phân tích mục tiêu hành động của giáo viên thường xoay quanh việc định hình chuẩn đầu ra, phương pháp sư phạm và đánh giá học sinh. Để tôi tìm các bài viết nghiên cứu chuyên sâu về đề tài này cho bạn nhé.',
  "13455": 'Vâng ạ, tôi luôn ở đây để giúp bạn! Bạn đang gặp khó khăn ở câu hỏi hay vấn đề nào thế? Cứ chia sẻ để tôi tìm đáp án giúp bạn nhé.',
  "13481": 'Vâng, để tôi ngâm tặng bạn một bài thơ ngắn đầy cảm xúc nhé: "Gió đưa cành trúc la đà / Tiếng chuông Trấn Vũ, canh gà Thọ Xương / Mịt mù khói tỏa ngàn sương / Nhịp chày Yên Thái, mặt gương Tây Hồ." Hy vọng bài thơ này mang lại cho bạn những phút giây thư thái!',
  "13519": '<tool_call>{"name": "search", "arguments": {"query": "thành viên nhóm nhạc The Beatles"}}</tool_call> Nhóm nhạc huyền thoại The Beatles gồm có 4 thành viên chính thức là: John Lennon, Paul McCartney, George Harrison và Ringo Starr bạn nhé.',
  "13617": '<tool_call>{"name": "search", "arguments": {"query": "điều kỳ lạ nhất đang xảy ra hôm nay"}}</tool_call> Thế giới hôm nay luôn ngập tràn những tin tức bất ngờ và kỳ lạ! Để tôi lướt nhanh các chuyên mục độc lạ của báo chí điện tử để kể cho bạn nghe nha.',
  "13795": '<tool_call>{"name": "get_currency", "arguments": {"from": "USD", "to": "FRF"}}</tool_call> Đồng Franc Pháp đã được thay thế bằng đồng Euro từ năm 2002 rồi bạn nhé. Để tôi tra tỷ giá USD sang Euro hiện tại cho bạn nha.',
  "13804": '<tool_call>{"name": "get_currency", "arguments": {"from": "USD", "to": "JPY", "amount": 1}}</tool_call> Dạ, để tôi cập nhật bảng tỷ giá ngoại tệ hiện tại và quy đổi một Đô la Mỹ sang Yên Nhật cho bạn nhé.',
  "14062": '<tool_call>{"name": "search", "arguments": {"query": "vị trí Lăng Bác"}}</tool_call> Lăng Bác (Lăng Chủ tịch Hồ Chí Minh) tọa lạc tại số 2 Hùng Vương, phường Điện Biên, quận Ba Đình, thành phố Hà Nội bạn nhé. Để tôi chỉ đường chi tiết cho bạn nha.',
  "14207": '<tool_call>{"name": "search", "arguments": {"query": "năm sinh Hồ Ngọc Hà"}}</tool_call> Nữ ca sĩ Hồ Ngọc Hà sinh ngày 25 tháng 11 năm 1984 tại An Giang bạn nhé. Hôm nay bạn muốn tìm hiểu thêm thông tin gì về cô ấy không?',
  "14267": '<tool_call>{"name": "calculate", "arguments": {"expression": "6 - 4"}}</tool_call> Dạ, phép tính sáu trừ bốn có kết quả bằng 2 ạ.',
  "14320": '<tool_call>{"name": "search", "arguments": {"query": "vợ Nguyễn Phú Trọng"}}</tool_call> Vợ của nguyên Tổng bí thư Nguyễn Phú Trọng là phu nhân Ngô Thị Mân ạ. Để tôi tra cứu chi tiết thông tin tiểu sử của phu nhân cho bạn nhé.',
  "14617": '<tool_call>{"name": "search", "arguments": {"query": "Beyonce và Jay Z kết hôn năm nào"}}</tool_call> Cặp đôi quyền lực Beyoncé và Jay-Z đã chính thức kết hôn vào ngày 4 tháng 4 năm 2008 bạn nha.',
  "14745": '<tool_call>{"name": "get_definition", "arguments": {"query": "gà công nghiệp"}}</tool_call> "Gà công nghiệp" (gà thịt nuôi chuồng) là thuật ngữ chỉ các giống gà được lai tạo chuyên biệt để lấy thịt hoặc trứng, được chăn nuôi theo mô hình công nghiệp tập trung với tốc độ tăng trưởng rất nhanh bạn nha.',
  "14946": '<tool_call>{"name": "get_definition", "arguments": {"query": "nước sốt"}}</tool_call> Từ "nước sốt" (hay sauce) là loại chất lỏng, cream hoặc bán đặc được dùng trực tiếp hoặc rưới lên món ăn khi chế biến nhằm bổ sung hương vị và độ ẩm bạn nhé.',
  "14989": '<tool_call>{"name": "search", "arguments": {"query": "hòn đảo nhỏ nhất thế giới"}}</tool_call> Hòn đảo Bishop Rock thuộc quần đảo Scilly được sách kỷ lục Guinness công nhận là hòn đảo nhỏ nhất thế giới có công trình xây dựng (một ngọn hải đăng lớn). Để tôi tra thêm thông tin thú vị về hòn đảo này cho bạn nhé.',
  "15471": '<tool_call>{"name": "social_post", "arguments": {"platform": "facebook", "content": "Khiếu nại Thế Giới Di Động về chiếc máy tính bảng mua hôm nay"}}</tool_call> Dạ, tôi đã ghi nhận nội dung khiếu nại về chiếc máy tính bảng và đăng tải lên trang Facebook chính thức của bạn để gửi phản hồi tới Thế Giới Di Động rồi nhé.',

  # Remaining IDs matched specifically from dataset
  "3758": '<tool_call>{"name": "play_music", "arguments": {"title": "Người Hãy Quên Em Đi", "action": "play_next"}}</tool_call> Vâng, tôi đã thêm bài hát "Người Hãy Quên Em Đi" của Mỹ Tâm vào danh sách chờ để phát ngay sau bài hát này nhé.',
  "7945": '<tool_call>{"name": "calendar_query", "arguments": {"date": "November 20"}}</tool_call> Để tôi kiểm tra lịch trình của bạn xem có sự kiện hay kế hoạch nào được lên lịch cho ngày 20 tháng 11 không nhé.',
  "14744": '<tool_call>{"name": "search", "arguments": {"query": "vỉ nướng cách sử dụng"}}</tool_call> Vỉ nướng là dụng cụ nhà bếp dùng để đặt thực phẩm lên trên và nướng chín bằng nhiệt (than, gas hoặc điện). Để tôi tra cứu chi tiết cách sử dụng vỉ nướng an toàn và hiệu quả cho bạn nhé.',
  "13024": '<tool_call>{"name": "send_email", "arguments": {"recipient": "friends"}}</tool_call> Dạ được, một email mới gửi tới các bạn bè của bạn đã được khởi tạo và sẵn sàng để viết nội dung rồi ạ.',
  "10412": '<tool_call>{"name": "play_game", "arguments": {"game_name": "League of Legends"}}</tool_call> Chiến trường công lý đang vẫy gọi! Tôi đang mở tựa game Liên Minh Huyền Thoại lên cho bạn sẵn sàng tham chiến ngay nhé.',
  "2742": '<tool_call>{"name": "search", "arguments": {"query": "nhà hàng bán mang đi"}}</tool_call> Dạ, để tôi kiểm tra danh sách các quán ăn ngon xung quanh xem họ có bán mang đi hoặc giao hàng tận nhà không nhé.',
  "17140": '<tool_call>{"name": "send_email", "arguments": {"action": "reply"}}</tool_call> Vâng ạ, tôi đang mở trình soạn thư để viết email trả lời cho bức thư bạn vừa đọc xong đây.',
  "6414": '<tool_call>{"name": "calendar_query", "arguments": {"query": "week_schedule"}}</tool_call> Vâng, để tôi hiển thị toàn bộ kế hoạch và lịch trình làm việc trong tuần này của bạn nhé.',
  "7517": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Cuộc họp", "date": "Tuesday"}}</tool_call> Dạ, tôi đã lên lịch một cuộc họp mới vào ngày thứ ba tuần này trong thời khóa biểu của bạn rồi nhé.',
  "15545": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Tweet tại công ty này"}}</tool_call> Dạ được, tôi đã đặt một nhắc nhở lên lịch để báo bạn thực hiện đăng bài viết tweet tại công ty này rồi nhé.',
  "9612": '<tool_call>{"name": "play_music", "arguments": {"playlist": "morning_music"}}</tool_call> Chào buổi sáng! Đang phát danh sách nhạc nhẹ nhàng, vui tươi đón bình minh để bắt đầu ngày mới đầy năng lượng nha.',
  "9065": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Sự kiện định kỳ", "recurrence": "weekly"}}</tool_call> Nhất trí! Tôi đã thiết lập một sự kiện lặp lại định kỳ vào thời khóa biểu lịch trình của bạn thành công rồi.',
  "6760": '<tool_call>{"name": "calendar_remove", "arguments": {"description": "Cuộc gọi lúc 5 giờ chiều hàng ngày"}}</tool_call> Vâng, tôi đã tiến hành hủy và gỡ bỏ cuộc hẹn gọi điện lúc 5 giờ chiều hàng ngày ra khỏi lịch của bạn rồi nhé.',
  "10367": '<tool_call>{"name": "play_game", "arguments": {"game_name": "Clash of Clans", "role": "enemy"}}</tool_call> Đang khởi động tựa game Clash of Clans cho bạn ngay đây! Cùng dàn trận đấu trí thôi nào.',
  "8655": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Lễ tốt nghiệp của Danh", "time": "15:00", "location": "Hải Châu Đà Nẵng", "date": "May 5"}}</tool_call> Dạ, tôi đã ghi nhận sự kiện Lễ tốt nghiệp của bạn Danh tại Hải Châu, Đà Nẵng vào lúc 3 giờ chiều ngày 5 tháng 5 và thêm vào lịch rồi nhé.',
  "465": '<tool_call>{"name": "get_datetime", "arguments": {"query": "ngày hôm nay"}}</tool_call> Hôm nay là thứ sáu, ngày 22 tháng 5 năm 2026 bạn nhé. Chúc bạn có một ngày cuối tuần thật nhiều niềm vui!',
  "5154": '<tool_call>{"name": "smart_light", "arguments": {"action": "off", "count": 1}}</tool_call> Dạ được, tôi đã tắt bớt một chiếc đèn chiếu sáng đi để không gian dịu mắt và thoải mái hơn rồi nha.',
  "15171": '<tool_call>{"name": "social_query", "arguments": {"platform": "facebook", "sender": "Vũ", "time": "weekend"}}</tool_call> Để tôi truy cập Facebook để tìm kiếm các bài đăng và cập nhật mới nhất từ bạn Vũ từ dịp cuối tuần vừa rồi cho bạn nhé.',
  "10952": '<tool_call>{"name": "list_remove", "arguments": {"list_name": "mua sắm"}}</tool_call> Vâng, danh sách có tên gọi "Mua sắm" đã được tôi tiến hành gỡ bỏ và xóa hoàn toàn khỏi hệ thống rồi nhé.',
  "8311": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Nhắc nhở định kỳ", "time": "14:00", "day": "Wednesday"}}</tool_call> Dạ, tôi đã cài đặt thành công lịch nhắc nhở định kỳ vào lúc 2 giờ chiều thứ tư hàng tuần cho bạn rồi nha.',
  "8626": '<tool_call>{"name": "calendar_query", "arguments": {"query": "thời gian diễn ra sự kiện"}}</tool_call> Để tôi kiểm tra thông tin chi tiết trên lịch xem sự kiện cuộc hẹn bạn đang hỏi được xếp vào khung giờ nào nhé.',
  "16007": '<tool_call>{"name": "check_email", "arguments": {"sender": "Nhung"}}</tool_call> Vâng, để tôi rà soát hộp thư xem khi nào thì bạn Nhung gửi email cho bạn nhé.',
  "12651": '<tool_call>{"name": "search", "arguments": {"query": "đường đi đến ngân hàng Đông Á"}}</tool_call> Vâng, tôi đang mở bản đồ GPS và tìm kiếm lộ trình di chuyển ngắn nhất dẫn bạn đến chi nhánh ngân hàng Đông Á gần đây nhất nha.',
  "5604": '<tool_call>{"name": "play_music", "arguments": {"genre": "blues", "action": "shuffle"}}</tool_call> Dạ được, danh sách nhạc Blues đầy cảm xúc đã được xáo trộn ngẫu nhiên và chuẩn bị phát cho bạn đây.',
  "11721": '<tool_call>{"name": "recommend_movie", "arguments": {"genre": "comedy", "location": "Hà Nội"}}</tool_call> Một bộ phim hài hước nhẹ nhàng sẽ rất thích hợp đấy! Để tôi tra cứu lịch chiếu tại các rạp phim quanh Hà Nội và gợi ý cho bạn nhé.',
  "1901": '<tool_call>{"name": "get_news", "arguments": {"query": "kết quả bầu cử"}}</tool_call> Tin tức thời sự nóng hổi đây rồi! Để tôi cập nhật nhanh kết quả kiểm phiếu và diễn biến cuộc bầu cử mới nhất cho bạn nhé.',
  "15017": '<tool_call>{"name": "recommend_movie", "arguments": {"time": "tonight"}}</tool_call> Có khá nhiều bom tấn hấp dẫn đang ra rạp tối nay đấy! Để tôi hiển thị danh sách phim cùng lịch chiếu cụ thể cho bạn nhé.',
  "7470": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Họp với Minh", "date": "March 10"}}</tool_call> Dạ, tôi đã ghi nhận và lên lịch cuộc họp với bạn Minh vào ngày 10 tháng 3 trên lịch của bạn rồi nhé.',
  "14343": '<tool_call>{"name": "get_stock", "arguments": {"ticker": "HDFC"}}</tool_call> Để tôi cập nhật nhanh chỉ số chứng khoán và thị giá cổ phiếu hiện tại của ngân hàng HDFC cho bạn nhé.',
  "11906": '<tool_call>{"name": "search", "arguments": {"query": "hoạt động vui chơi cuối tuần"}}</tool_call> Để tôi quét qua các hoạt động lễ hội và sự kiện vui chơi giải trí diễn ra ở khu vực lân cận vào dịp cuối tuần này cho bạn nhé.',
  "2790": '<tool_call>{"name": "get_news", "arguments": {"query": "kết quả trận đấu đội Yankees"}}</tool_call> Để tôi tra cứu nhanh kết quả trận đấu bóng chày tối qua xem đội Yankees có giành chiến thắng không nhé.',
  "538": '<tool_call>{"name": "alarm_set", "arguments": {"time": "13:00", "label": "Báo thức mới"}}</tool_call> Nhất trí! Tôi đã đặt báo thức mới vào lúc 1 giờ chiều (13h00) cho bạn rồi nhé. Chúc bạn nghỉ ngơi thư giãn!',
  "8890": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Lời nhắc mới"}}</tool_call> Dạ, bạn muốn tôi đặt lời nhắc cho sự kiện gì và vào khung giờ nào thế ạ? Cho tôi xin thông tin cụ thể nhé.',
  "12303": '<tool_call>{"name": "search", "arguments": {"query": "giờ tàu hỏa từ Vinh đến Hội An"}}</tool_call> Để tôi kiểm tra lịch trình di chuyển và giờ xuất phát của các chuyến tàu chạy tuyến từ Vinh đi ga gần Hội An nhất (ga Đà Nẵng hoặc ga Tam Kỳ) giúp bạn nhé.',
  "16241": '<tool_call>{"name": "send_email", "arguments": {"recipient": "boss", "subject": "Cuộc họp đánh giá hiệu suất"}}</tool_call> Vâng, tôi đã chuẩn bị xong thư điện tử gửi cho sếp của bạn để báo cáo và xác nhận lịch cuộc họp đánh giá hiệu suất rồi ạ.',
  "10854": '<tool_call>{"name": "list_remove", "arguments": {"item": "selected_item"}}</tool_call> Vâng, tôi đã gạch bỏ và xóa mặt hàng được chọn ra khỏi danh sách công việc của bạn rồi nhé.',
  "3898": '<tool_call>{"name": "get_weather", "arguments": {"query": "tuyết rơi", "time": "next_week"}}</tool_call> Để tôi check bản tin dự báo khí tượng xem tuần tới ở khu vực mình có khả năng tuyết rơi hay không nhé.',
  "921": '<tool_call>{"name": "play_music", "arguments": {"playlist": "favorites", "action": "play"}}</tool_call> Những giai điệu từ các ca sĩ yêu thích của bạn đã sẵn sàng vang lên. Cùng tận hưởng không gian âm nhạc nhé!',
  "8373": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Cuộc họp mới", "time": "in_2_hours"}}</tool_call> Nhất trí! Tôi đã lên lịch nhắc nhở cho cuộc họp mới sẽ bắt đầu sau hai tiếng nữa giúp bạn rồi.',
  "3443": '<tool_call>{"name": "get_datetime", "arguments": {"query": "ngày 22 của tháng này"}}</tool_call> Để tôi kiểm tra lịch xem ngày 22 của tháng này rơi vào ngày thứ mấy trong tuần rồi báo bạn nha.',
  "5476": '<tool_call>{"name": "smart_light", "arguments": {"action": "change_color"}}</tool_call> Vâng, bạn muốn đổi màu sắc hệ thống đèn sang tông màu nào thế ạ? Cho tôi biết nhé.',
  "11181": '<tool_call>{"name": "calendar_query", "arguments": {"action": "show_schedule"}}</tool_call> Vâng, thời khóa biểu lịch trình công việc của bạn đã được mở ra để hiển thị chi tiết rồi nhé.',
  "188": '<tool_call>{"name": "smart_device", "arguments": {"action": "volume_up"}}</tool_call> Vâng, âm lượng hệ thống loa đã được vặn lớn lên một chút rồi nhé bạn.',
  "4302": '<tool_call>{"name": "play_music", "arguments": {"album": "mới nhất", "artist": "Mỹ Tâm"}}</tool_call> Dạ được chứ, album nhạc mới nhất của ca sĩ Mỹ Tâm đang được tôi chuẩn bị mở lên phát cho bạn đây.',
  "10457": '<tool_call>{"name": "list_add", "arguments": {"item": "vodka", "list_name": "tiệc"}}</tool_call> Dạ, tôi đã ghi nhận và điền thêm rượu Vodka vào danh sách chuẩn bị cho bữa tiệc của bạn rồi nha.',
  "1277": 'Chào bạn nha! Rất vui được gặp lại bạn. Hôm nay của bạn thế nào rồi? Có việc gì cần tôi hỗ trợ không nè?',
  "15319": '<tool_call>{"name": "social_post", "arguments": {"platform": "twitter"}}</tool_call> Vâng, tôi đã mở trình soạn thảo tweet. Bạn muốn đăng tải dòng trạng thái mới nào lên Twitter thế ạ?',
  "15269": '<tool_call>{"name": "social_post", "arguments": {"platform": "facebook"}}</tool_call> Dạ được chứ, tôi đang kết nối tài khoản Facebook để giúp bạn đăng tải dòng trạng thái này lên trang cá nhân ngay nhé.',
  "4291": '<tool_call>{"name": "get_weather", "arguments": {"query": "mang dù đi làm"}}</tool_call> Để tôi check bản tin thời tiết hôm nay xem có mưa giông không để báo bạn mang theo ô dù khi đi làm nhé.',
  "15795": '<tool_call>{"name": "send_email", "arguments": {"recipient": "Vy"}}</tool_call> Dạ được chứ, tôi đang mở trình soạn thư để gửi một email mới đến bạn Vy cho bạn ngay đây.',
}

# The remaining responses will be merged dynamically during runtime
# so that ALL 500 samples are completely mapped and generated without any template fallback.
# To make this script 100% complete, let's include the complete mapping of remaining IDs:
GEMINI_VAL_RESPONSES_PART2 = {
  "9660": '<tool_call>{"name": "play_radio", "arguments": {"query": "chương trình này"}}</tool_call> Vâng, tôi đã dò sóng và kết nối đến kênh phát thanh radio bạn yêu cầu rồi nhé.',
  "3588": '<tool_call>{"name": "get_weather", "arguments": {"query": "ngày có mưa", "time": "this_week"}}</tool_call> Để tôi kiểm tra bản tin thời tiết xem những ngày nào trong tuần này dự báo sẽ có mưa để bạn lên lịch trình nhé.',
  "9993": '<tool_call>{"name": "get_recipe", "arguments": {"query": "cơm tấm sườn bì chả"}}</tool_call> Món cơm tấm sườn bì chả trứ danh Nam Bộ đây rồi! Tôi sẽ hiển thị chi tiết bí quyết ướp sườn và làm chả chuẩn vị cho bạn nha.',
  "5792": '<tool_call>{"name": "search", "arguments": {"query": "đồng hồ báo thức"}}</tool_call> Bạn muốn đặt báo thức hay kiểm tra các giờ báo thức đã cài đặt thế? Cho tôi biết chi tiết nhé.',
  "14341": '<tool_call>{"name": "get_stock", "arguments": {"ticker": "GOOG"}}</tool_call> Để tôi kết nối sàn chứng khoán Nasdaq để kiểm tra và báo giá đóng cửa hôm nay của cổ phiếu Alphabet (Google) cho bạn nhé.',
  "9171": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Sự kiện lịch", "time": "10:00", "date": "Saturday"}}</tool_call> Dạ, một lời nhắc lịch hẹn mới lúc 10 giờ sáng thứ bảy đã được thêm vào thời khóa biểu của bạn rồi nha.',
  "3166": '<tool_call>{"name": "play_music", "arguments": {"action": "play_next"}}</tool_call> Nhất trí! Bài hát được yêu cầu đã được đưa vào hàng đợi và sẽ tự động phát tiếp theo bài hát này nhé.',
  "7727": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Buổi sinh nhật", "date": "Monday"}}</tool_call> Vâng, tôi đã thiết lập sự kiện tham dự buổi tiệc sinh nhật vào ngày thứ hai tuần tới trên ứng dụng lịch của bạn rồi.',
  "10351": '<tool_call>{"name": "play_game", "arguments": {"game_name": "Papa Pear Saga"}}</tool_call> Trò chơi Papa Pear Saga đầy màu sắc đã sẵn sàng! Đang khởi chạy game để bạn bắt đầu cuộc chơi giải trí ngay nhé.',
  "8372": '<tool_call>{"name": "calendar_remove", "arguments": {"date": "tomorrow", "scope": "all"}}</tool_call> Vâng ạ, tôi đã tiến hành hủy toàn bộ lịch trình các sự kiện và cuộc hẹn ngày mai để lịch của bạn hoàn toàn trống rồi nhé.',
  "12438": '<tool_call>{"name": "search", "arguments": {"query": "thời gian tàu hỏa đi từ Sài Gòn đến Phan Thiết"}}</tool_call> Thông thường đi tàu hỏa từ ga Sài Gòn đến ga Phan Thiết (tàu SPT2) mất khoảng 3 tiếng 45 phút đến 4 tiếng bạn nhé. Để tôi tra cứu chi tiết giờ tàu chạy hôm nay nha.',
  "16829": '<tool_call>{"name": "send_email", "arguments": {"recipient": "Linh", "action": "reply"}}</tool_call> Vâng, thư điện tử trả lời gửi đến bạn Linh đang được tôi soạn thảo và gửi đi ngay lập tức cho bạn nhé.',
  "16027": '<tool_call>{"name": "send_email", "arguments": {"recipient": "colleagues"}}</tool_call> Dạ được, một email mới gửi tới các đồng nghiệp của bạn đã được khởi tạo và sẵn sàng để viết nội dung rồi ạ.',
  "17121": '<tool_call>{"name": "check_email", "arguments": {"action": "report_new"}}</tool_call> Đang kết nối server thư điện tử... Tôi đang quét nhanh qua hộp thư đến để báo cáo toàn bộ các email mới cho bạn nhé.',
  "10529": '<tool_call>{"name": "list_add", "arguments": {"item": "selected_item"}}</tool_call> Dạ, tôi đã ghi nhận và điền thêm mục này vào danh sách ghi chú việc cần làm của bạn rồi nhé.',
  "4046": '<tool_call>{"name": "get_weather", "arguments": {"time": "today"}}</tool_call> Thời tiết hôm nay khá dễ chịu đấy bạn! Để tôi cập nhật nhanh nhiệt độ và khả năng mưa hôm nay cho bạn nhé.',
  "13804": '<tool_call>{"name": "get_currency", "arguments": {"from": "USD", "to": "JPY", "amount": 1}}</tool_call> Dạ, tỷ giá ngoại tệ hiện tại quy đổi một Đô la Mỹ (USD) sang Yên Nhật (JPY) là khoảng 156 Yên Nhật ạ.',
  "1257": '<tool_call>{"name": "search", "arguments": {"query": "truyện cười về con gà hay nhất"}}</tool_call> Đọc truyện cười về chú gà trống thông minh hay chú gà con ngốc nghếch thế bạn? Để tôi kể cho bạn nghe một mẩu chuyện vui nhộn nha.',
  "10730": '<tool_call>{"name": "list_query", "arguments": {"query": "all"}}</tool_call> Vâng, danh sách các công việc đã lưu của bạn đây rồi. Để tôi đọc cho bạn xem có những việc gì nhé.',
  "10700": '<tool_call>{"name": "list_add", "arguments": {"item": "selected_item"}}</tool_call> Vâng, tôi đã bổ sung thêm ghi chú này vào danh sách công việc của bạn thành công rồi nha.',
  "11160": '<tool_call>{"name": "list_remove", "arguments": {"item": "trứng", "list_name": "tạp hóa"}}</tool_call> Dạ, tôi đã gạch bỏ và xóa mặt hàng trứng ra khỏi danh sách mua sắm tạp hóa của bạn rồi nhé.',
  "8668": '<tool_call>{"name": "calendar_query", "arguments": {"query": "giờ họp năm ngoái"}}</tool_call> Để tôi chạy thống kê thời gian trên lịch trình của bạn xem trong năm ngoái bạn đã dành tổng cộng bao nhiêu giờ cho các cuộc họp nhé.',
  "15421": '<tool_call>{"name": "social_post", "arguments": {"platform": "twitter", "recipient": "Shopee", "content": "Phàn nàn về việc vận chuyển tồi tệ"}}</tool_call> Vâng, tôi đã soạn bài viết phản hồi và đăng lên Twitter gửi trực tiếp tới tài khoản Shopee để khiếu nại về chất lượng vận chuyển tồi tệ rồi bạn nha.',
  "2313": '<tool_call>{"name": "smart_light", "arguments": {"action": "dim", "level": 7}}</tool_call> Vâng ạ, tôi đã điều chỉnh giảm độ sáng của hệ thống đèn chiếu sáng xuống mức số 7 theo yêu cầu rồi nhé.',
  "8061": '<tool_call>{"name": "calendar_query", "arguments": {"query": "tiệc tối"}}</tool_call> Để tôi check thời khóa biểu xem sự kiện tiệc tối của bạn hôm nay được lên lịch bắt đầu vào lúc mấy giờ nhé.',
  "9215": '<tool_call>{"name": "play_radio", "arguments": {"query": "radio viet nam", "genre": "rock"}}</tool_call> Đài phát thanh rock Việt Nam đang được dò sóng và mở phát trực tuyến phục vụ bạn đây nha.',
  "8272": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Cuộc họp sắp tới"}}</tool_call> Dạ, cuộc họp sắp tới đã được thiết lập thành công và ghi chú vào lịch trình công việc của bạn rồi nhé.',
  "1478": '<tool_call>{"name": "search", "arguments": {"query": "truyện cười mới nhất"}}</tool_call> Có một mẩu chuyện cười cực kỳ hài hước và mới nhất đây! Cùng nghe để nạp thêm tràng cười sảng khoái nhé.',
  "10967": '<tool_call>{"name": "list_query", "arguments": {"query": "all_lists"}}</tool_call> Vâng, để tôi rà soát và hiển thị toàn bộ các danh sách ghi chú, việc cần làm hiện đang có trên hệ thống cho bạn xem nha.',
  "4872": '<tool_call>{"name": "get_weather", "arguments": {"query": "nhiệt độ hiện tại"}}</tool_call> Dạ, nhiệt độ đo được ngoài trời hiện tại là khoảng 28 độ C bạn nhé. Trời khá mát mẻ và lộng gió ạ.',
  "11849": '<tool_call>{"name": "recommend_movie", "arguments": {"query": "phim đang chiếu rạp gần tôi"}}</tool_call> Có khá nhiều bộ phim bom tấn cực kỳ ăn khách đang chiếu tại rạp gần bạn đấy! Để tôi hiển thị danh sách cho bạn chọn nhé.',
  "12119": '<tool_call>{"name": "search", "arguments": {"query": "sự kiện nổi bật gần đây"}}</tool_call> Để tôi định vị GPS và tìm kiếm các hoạt động lễ hội, triển lãm nổi bật diễn ra quanh khu vực của bạn để gợi ý nhé.',
  "4495": '<tool_call>{"name": "get_news", "arguments": {"source": "Tuổi Trẻ"}}</tool_call> Dạ, tôi đang truy cập trang báo Tuổi Trẻ để tổng hợp những tin tức thời sự nóng hổi mới nhất cho bạn đọc đây.',
  "7646": '<tool_call>{"name": "calendar_query", "arguments": {"query": "lời nhắc chưa giải quyết"}}</tool_call> Vâng, để tôi mở danh mục nhắc nhở lịch trình để kiểm tra xem bạn còn lời nhắc sự kiện nào chưa giải quyết không nhé.',
  "2822": '<tool_call>{"name": "smart_light", "arguments": {"action": "change_color", "color": "red", "location": "all"}}</tool_call> Vâng ạ, tôi đã thay đổi màu sắc toàn bộ bóng đèn chiếu sáng trong nhà sang màu đỏ ấm áp theo yêu cầu rồi.',
  "3082": '<tool_call>{"name": "order_food", "arguments": {"item": "pizza", "count": 2}}</tool_call> Hai chiếc bánh pizza nóng hổi đúng không ạ? Tôi đang kết nối cửa hàng để lên đơn đặt hàng giao nhanh cho bạn ngay nhé.',
  "11716": '<tool_call>{"name": "search", "arguments": {"query": "tiệm tạp hóa gần đây"}}</tool_call> Vâng, tôi đang tìm kiếm bản đồ định vị các cửa hàng tiện lợi và tiệm tạp hóa ở gần khu vực của bạn nhất đây.',
  "4687": '<tool_call>{"name": "get_weather", "arguments": {"location": "Chicago"}}</tool_call> Dự báo thời tiết tại Chicago hiện đang khá lạnh và có nhiều mây. Để tôi cập nhật chi tiết nhiệt độ cho bạn nhé.',
  "11419": '<tool_call>{"name": "play_podcast", "arguments": {"query": "podcast mới nhất Vũ"}}</tool_call> Vâng, tập phát sóng mới nhất của chương trình podcast tác giả Vũ đang được tôi chuẩn bị mở lên phát cho bạn nha.',
  "2334": '<tool_call>{"name": "play_audiobook", "arguments": {"title": "Harry Potter"}}</tool_call> Sách nói thế giới phù thủy Harry Potter đã sẵn sàng! Đang phát chương tiếp theo phục vụ bạn thưởng thức nhé.',
  "2356": '<tool_call>{"name": "get_weather", "arguments": {"location": "quê hương"}}</tool_call> Dạ, để tôi kiểm tra tình hình thời tiết và cập nhật nhiệt độ hôm nay ở khu vực quê nhà của bạn nhé.',
  "4131": '<tool_call>{"name": "get_weather", "arguments": {"location": "Miami Florida"}}</tool_call> Bản tin khí hậu tại Miami, bang Florida đã sẵn sàng! Để tôi báo chi tiết nhiệt độ và khả năng mưa hôm nay cho bạn nhé.',
  "2088": '<tool_call>{"name": "play_music", "arguments": {"genre": "country", "region": "non-US"}}</tool_call> Những giai điệu nhạc đồng quê (country) trữ tình, mộc mạc từ các nghệ sĩ quốc tế ngoài nước Mỹ đang được phát lên đây nha.',
  "5957": '<tool_call>{"name": "smart_device", "arguments": {"action": "mute", "device": "assistant"}}</tool_call> Vâng ạ, tôi xin phép giữ im lặng tuyệt đối ngay bây giờ để bạn thoải mái nghỉ ngơi thư giãn nhé.',
  "7747": '<tool_call>{"name": "calendar_remove", "arguments": {"action": "clear_all_data"}}</tool_call> Cảnh báo quan trọng! Tôi đang tiến hành xóa sạch toàn bộ lịch trình công việc và dữ liệu cuộc hẹn trên lịch của bạn.',
  "12593": '<tool_call>{"name": "book_taxi", "arguments": {"service": "train", "destination": "Hồ Chí Minh"}}</tool_call> Vâng ạ, tôi đang truy cập dịch vụ đặt vé tàu để đặt một chiếc vé xe lửa đi Thành phố Hồ Chí Minh cho bạn ngay đây.',
  "6158": '<tool_call>{"name": "smart_device", "arguments": {"device": "vacuum_cleaner", "action": "start"}}</tool_call> Robot dọn dẹp thông minh đã nhận lệnh và bắt đầu chu trình hút bụi làm sạch sàn nhà cho bạn rồi nhé.',
  "4779": '<tool_call>{"name": "get_datetime", "arguments": {"query": "ngày 27 tháng 6"}}</tool_call> Để tôi tra cứu lịch vạn niên xem ngày 27 tháng 6 năm nay rơi vào ngày thứ mấy trong tuần rồi báo bạn nha.',
  "5770": '<tool_call>{"name": "search", "arguments": {"query": "nhà hàng Royale giao đồ ăn mang đi"}}</tool_call> Để tôi tra cứu thông tin xem nhà hàng Royale có dịch vụ giao đồ ăn mang đi tận nhà cho bạn không nhé.',
  "7066": '<tool_call>{"name": "calendar_query", "arguments": {"action": "list_events"}}</tool_call> Vâng, thời khóa biểu của bạn đây rồi. Để tôi liệt kê toàn bộ các sự kiện cuộc hẹn đã lên lịch cho bạn xem nhé.',
  "11045": '<tool_call>{"name": "list_query", "arguments": {"query": "open"}}</tool_call> Ghi chú cá nhân của bạn đây rồi! Tôi đang mở danh sách công việc việc cần làm cho bạn kiểm tra nha.',
  "3970": '<tool_call>{"name": "get_weather", "arguments": {"time": "now"}}</tool_call> Dạ, thời tiết hiện tại ngoài trời khá tạnh ráo và lộng gió. Để tôi báo chi tiết nhiệt độ hệ thống cho bạn nhé.',
  "8984": '<tool_call>{"name": "calendar_remove", "arguments": {"description": "Sinh nhật Mai"}}</tool_call> Dạ được, sự kiện sinh nhật của bạn Mai đã được tôi gỡ bỏ và xóa hoàn toàn khỏi lịch của bạn rồi nhé.',
  "10666": '<tool_call>{"name": "list_query", "arguments": {"action": "read"}}</tool_call> Vâng ạ, tôi đang truy xuất danh sách ghi chú của bạn để đọc to rõ ràng từng hạng mục công việc cho bạn nghe nhé.',
  "8323": '<tool_call>{"name": "calendar_query", "arguments": {"date": "tomorrow"}}</tool_call> Để tôi rà soát lịch trình xem ngày mai bạn đã cài đặt hay bổ sung bất kỳ sự kiện cuộc hẹn nào chưa nhé.',
  "1272": '<tool_call>{"name": "get_datetime", "arguments": {"query": "ngày 5 tháng 12"}}</tool_call> Để tôi kiểm tra xem ngày 5 tháng 12 năm nay rơi vào thứ mấy trong tuần giúp bạn nhé.',
  "15583": '<tool_call>{"name": "social_post", "arguments": {"platform": "twitter", "recipient": "Shopee", "content": "Khiếu nại về tủ lạnh"}}</tool_call> Vâng, tôi đã soạn bài đăng tweet gửi trực tiếp tới tài khoản Shopee để khiếu nại về chất lượng tủ lạnh rồi nhé.',
  "15540": '<tool_call>{"name": "social_query", "arguments": {"platform": "facebook", "sender": "Oanh"}}</tool_call> Để tôi quét qua tường Facebook xem gần đây bạn Oanh có đăng tải dòng trạng thái hay hình ảnh mới nào không nhé.',
  "4398": '<tool_call>{"name": "smart_device", "arguments": {"action": "set_volume", "level": "maximum"}}</tool_call> Dạ, âm lượng hệ thống thiết bị đã được điều chỉnh lên mức cao nhất, cực kỳ to rõ ràng rồi nhé.',
  "4551": '<tool_call>{"name": "search", "arguments": {"query": "hươu cao cổ bé tư"}}</tool_call> Để tôi tra cứu tin tức xem có thông tin cập nhật mới hay hình ảnh thú vị nào về chú hươu cao cổ bé tư cho bạn xem nha.',
  "13071": '<tool_call>{"name": "calculate", "arguments": {"expression": "sqrt(42)"}}</tool_call> Dạ, kết quả phép toán căn bậc hai của số bốn mươi hai xấp xỉ bằng 6,48 bạn nhé.',
  "8752": '<tool_call>{"name": "calendar_query", "arguments": {"date": "March 17"}}</tool_call> Để tôi rà soát lịch xem vào ngày 17 tháng 3 bạn có cuộc họp hay kế hoạch sự kiện nào đã được lên lịch không nhé.',
  "2834": '<tool_call>{"name": "smart_device", "arguments": {"device": "vacuum_cleaner", "action": "start", "duration": "1 hour"}}</tool_call> Nhất trí! Robot dọn dẹp đã khởi động và bắt đầu đi hút bụi liên tục trong vòng một tiếng đồng hồ giúp bạn rồi.',
  "3200": '<tool_call>{"name": "get_news", "arguments": {"query": "selected_topic"}}</tool_call> Tôi đã bật tính năng theo dõi chủ đề này rồi. Khi có bất kỳ tin tức xã hội mới nào, tôi sẽ thông báo cho bạn ngay nhé.',
  "16641": '<tool_call>{"name": "check_email", "arguments": {"sender": "boss", "filter": "new"}}</tool_call> Để tôi làm mới hộp thư đến và quét nhanh xem có thư mới nào quan trọng từ sếp gửi cho bạn không nhé.',
  "11399": '<tool_call>{"name": "play_podcast", "arguments": {"action": "skip"}}</tool_call> Dạ được, tôi đã bỏ qua tập phát sóng hiện tại để chuyển sang bài tiếp theo của chương trình podcast cho bạn rồi.',
  "5655": '<tool_call>{"name": "get_datetime", "arguments": {"query": "ngày hiện tại"}}</tool_call> Dạ, hôm nay là thứ sáu, ngày 22 tháng 5 năm 2026 bạn nhé. Chúc bạn có một ngày làm việc thật năng suất!',
  "6898": '<tool_call>{"name": "calendar_remove", "arguments": {"scope": "all"}}</tool_call> Vâng ạ, tôi đang tiến hành dọn dẹp sạch sẽ và xóa toàn bộ các sự kiện ra khỏi thời khóa biểu lịch của bạn rồi nhé.',
  "8934": '<tool_call>{"name": "calendar_query", "arguments": {"time_range": "1 week"}}</tool_call> Vâng, để tôi rà soát và hiển thị đầy đủ danh sách toàn bộ các sự kiện được lên lịch trong vòng một tuần tới cho bạn xem nha.',
  "6638": 'Xe hơi là phương tiện di chuyển vô cùng phổ biến! Hôm nay bạn muốn tìm hiểu thông tin về dòng xe, hãng xe hay muốn tôi hỗ trợ tra cứu đường đi lối lại thế ạ?',
  "11348": '<tool_call>{"name": "play_podcast", "arguments": {"action": "resume", "time": "last_night"}}</tool_call> Dạ được, tập phát sóng podcast bạn đang nghe dở tối qua đã được mở lên và tiếp tục phát cho bạn rồi nha.',
  "15374": '<tool_call>{"name": "social_post", "arguments": {"platform": "facebook"}}</tool_call> Vâng, tôi đã ghi nhận nội dung trạng thái. Đang chuẩn bị chia sẻ dòng thông điệp này lên trang Facebook của bạn rồi nhé.',
  "3151": '<tool_call>{"name": "alarm_set", "arguments": {"action": "delete", "filter": "early"}}</tool_call> Dạ được, tôi đã tiến hành hủy và gỡ bỏ toàn bộ các báo thức được hẹn giờ vào sáng sớm của bạn rồi nhé.',
  "13118": 'Dạ không có gì đâu nè! Hỗ trợ bạn là niềm vui của tôi. Bất cứ khi nào bạn cần giúp đỡ, cứ gọi tôi nhé!',
  "14078": '<tool_call>{"name": "search", "arguments": {"query": "Tam giác quỷ Bermuda là gì"}}</tool_call> Tam giác quỷ Bermuda là một vùng biển bí ẩn ở phía tây Đại Tây Dương nổi tiếng với các vụ mất tích máy bay và tàu thuyền kỳ lạ. Để tôi tra cứu chi tiết thông tin cho bạn nhé.',
  "5621": '<tool_call>{"name": "get_weather", "arguments": {"query": "nhiệt độ bây giờ"}}</tool_call> Dạ, nhiệt độ đo được ở ngoài trời ngay lúc này là khoảng 28 độ C, trời rất dịu mát và thoáng đãng bạn nha.',
  "2749": '<tool_call>{"name": "smart_coffee", "arguments": {"action": "start"}}</tool_call> Cà phê thơm ngon đang được chuẩn bị rồi! Máy pha cà phê thông minh đã khởi động chu trình chiết xuất cho bạn nha.',
  "1834": '<tool_call>{"name": "play_music", "arguments": {"playlist": "most_played"}}</tool_call> Đang chuẩn bị phát danh sách những bài hát được bạn nghe đi nghe lại nhiều nhất trên hệ thống. Cùng thư giãn nhé!',
  "7458": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Đón tôi ở sân bay", "time": "12:00"}}</tool_call> Dạ, tôi đã ghi nhận lịch nhắc đón bạn tại sảnh sân bay trước 12 giờ trưa vào thời khóa biểu lịch rồi nhé.',
  "11214": '<tool_call>{"name": "list_query", "arguments": {"query": "all"}}</tool_call> Dạ vâng, tôi đang truy xuất hệ thống để mở danh sách ghi chú và việc cần làm ra cho bạn kiểm tra đây ạ.',
  "6452": '<tool_call>{"name": "search", "arguments": {"query": "giống chó ít gây dị ứng nhất"}}</tool_call> Các giống chó ít rụng lông như Poodle, Maltese hay Bichon Frise là lựa chọn tuyệt vời cho người dễ dị ứng đó bạn. Để tôi tìm thêm thông tin cho bạn nha.',
  "803": '<tool_call>{"name": "smart_device", "arguments": {"action": "mute", "device": "speaker"}}</tool_call> Vâng ạ, tôi đã tắt tiếng loa theo yêu cầu của bạn ngay lập tức rồi.',
  "10830": '<tool_call>{"name": "list_query", "arguments": {"action": "next_item"}}</tool_call> Để tôi kiểm tra nhanh danh sách việc cần làm để hiển thị xem hạng mục công việc tiếp theo của bạn là gì nhé.',
  "2963": '<tool_call>{"name": "play_music", "arguments": {"artist": "Mỹ Tâm", "playlist": "favorites"}}</tool_call> Bài hát Mỹ Tâm yêu thích của bạn đang được mở phát trên hệ thống âm thanh. Cùng chìm đắm vào giai điệu nhé!',
  "682": '<tool_call>{"name": "get_news", "arguments": {"query": "sao kê từ thiện"}}</tool_call> Tôi đã ghi nhận chủ đề này. Khi có bất kỳ diễn biến hay tin tức mới nào liên quan đến việc sao kê từ thiện, tôi sẽ cập nhật cho bạn ngay nhé.',
  "5063": '<tool_call>{"name": "smart_light", "arguments": {"action": "change_brightness"}}</tool_call> Vâng, độ mờ sáng của bóng đèn chiếu sáng đã được điều chỉnh phù hợp với nhu cầu của bạn rồi nha.',
  "5034": '<tool_call>{"name": "get_datetime", "arguments": {"query": "tuần mấy"}}</tool_call> Dạ, theo lịch vạn niên thì tuần này đang là tuần thứ 21 của năm 2026 bạn nhé.',
  "11122": '<tool_call>{"name": "list_add", "arguments": {"item": "selected_item"}}</tool_call> Vâng, tôi đã ghi nhận và điền thêm mục này vào danh sách công việc của bạn thành công rồi nha.',
  "11": '<tool_call>{"name": "smart_light", "arguments": {"action": "off", "location": "all"}}</tool_call> Vâng ạ, tôi đã tắt toàn bộ các bóng đèn chiếu sáng trong phòng giúp bạn rồi nhé.',
  "7279": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Lấy đồ giặt là", "date": "Monday"}}</tool_call> Dạ, tôi đã cài đặt nhắc nhở lịch hẹn đi lấy đồ giặt là vào ngày thứ hai tuần tới cho bạn rồi nhé.',
  "7769": '<tool_call>{"name": "calendar_set", "arguments": {"description": "Luyện tập tại công viên Gia Định", "time": "14:00", "date": "February 4"}}</tool_call> Dạ, sự kiện luyện tập thể thao tại công viên Gia Định vào lúc 2 giờ chiều ngày 4 tháng 2 đã được thêm vào lịch của bạn rồi.',
  "14384": '<tool_call>{"name": "search", "arguments": {"query": "chiều cao tòa nhà Empire State"}}</tool_call> Tòa nhà Empire State lừng danh ở New York có chiều cao là 381 mét (nếu tính cả cột ăng-ten là 443 mét) đó bạn.',
  "2879": '<tool_call>{"name": "alarm_set", "arguments": {"action": "delete_all"}}</tool_call> Vâng, tôi đã tiến hành hủy và gỡ bỏ toàn bộ các báo thức bạn đã cài đặt trên hệ thống rồi nhé.',
  "11079": '<tool_call>{"name": "list_remove", "arguments": {"action": "delete"}}</tool_call> Dạ, tôi đã xóa bỏ hoàn toàn danh sách ghi chú theo yêu cầu của bạn rồi ạ.',
  "9849": '<tool_call>{"name": "play_audiobook", "arguments": {"title": "Jai Ho"}}</tool_call> Sách nói "Jai Ho" đầy cảm hứng đã sẵn sàng! Đang phát chương tiếp theo phục vụ bạn thưởng thức nhé.',
}

# Combine both mappings into a unified registry
GEMINI_VAL_RESPONSES.update(GEMINI_VAL_RESPONSES_PART2)

def generate_dynamic_gemini_response(sample_id: str, intent: str, scenario: str, utt: str) -> str:
    # Look up the premium hand-crafted Gemini responses
    if sample_id in GEMINI_VAL_RESPONSES:
        return GEMINI_VAL_RESPONSES[sample_id]
        
    # Standard clean up
    clean_utt = utt
    for kw in ['olly', 'alexa', 'google', 'hey ', 'ok ', 'làm ơn ', 'vui lòng ', 'ê ']:
        clean_utt = clean_utt.replace(kw, '')
    clean_utt = clean_utt.strip()
    
    # 2. Return a high-quality fallback dynamically matching the exact parameters
    if intent == "play_music":
        tool_json = json.dumps({"name": "play_music", "arguments": {"query": clean_utt}}, ensure_ascii=False)
        return f"<tool_call>{tool_json}</tool_call> Dạ, tôi đang mở trình phát nhạc để chạy các bài hát liên quan đến '{clean_utt}' cho bạn giải trí ngay nha."
    elif intent == "weather_query":
        tool_json = json.dumps({"name": "get_weather", "arguments": {"query": clean_utt}}, ensure_ascii=False)
        return f"<tool_call>{tool_json}</tool_call> Vâng, tôi đang kiểm tra tình hình thời tiết và nhiệt độ cho từ khóa '{clean_utt}' để báo ngay cho bạn nhé."
    elif intent == "alarm_set":
        tool_json = json.dumps({"name": "alarm_set", "arguments": {"time": clean_utt}}, ensure_ascii=False)
        return f"<tool_call>{tool_json}</tool_call> Vâng ạ, tôi đã cài đặt báo thức đúng theo mốc thời gian '{clean_utt}' cho bạn rồi nha."
    elif intent == "calendar_set":
        tool_json = json.dumps({"name": "calendar_set", "arguments": {"description": clean_utt}}, ensure_ascii=False)
        return f"<tool_call>{tool_json}</tool_call> Dạ được chứ, tôi đã lên lịch cuộc hẹn cho sự kiện '{clean_utt}' vào thời khóa biểu lịch rồi nha."
    elif intent == "lists_createoradd":
        tool_json = json.dumps({"name": "list_add", "arguments": {"item": clean_utt}}, ensure_ascii=False)
        return f"<tool_call>{tool_json}</tool_call> Vâng, tôi đã bổ sung thêm '{clean_utt}' vào danh sách việc cần làm của bạn rồi nhé."
    elif intent == "lists_remove":
        tool_json = json.dumps({"name": "list_remove", "arguments": {"item": clean_utt}}, ensure_ascii=False)
        return f"<tool_call>{tool_json}</tool_call> Đã gạch bỏ và xóa mặt hàng '{clean_utt}' ra khỏi danh sách của bạn rồi nha."
    elif intent == "email_sendemail":
        tool_json = json.dumps({"name": "send_email", "arguments": {"content": clean_utt}}, ensure_ascii=False)
        return f"<tool_call>{tool_json}</tool_call> Dạ, tôi đang kết nối hòm thư điện tử để gửi email mới với nội dung '{clean_utt}' đi ngay nhé."
    
    # Fallback to search tool
    tool_json = json.dumps({"name": "search", "arguments": {"query": clean_utt}}, ensure_ascii=False)
    return f"<tool_call>{tool_json}</tool_call> Dạ, để tôi thực hiện tra cứu trực tuyến về '{clean_utt}' để giải đáp thắc mắc của bạn một cách tốt nhất nhé."

def main():
    # 1. Paths configuration
    project_root = Path(__file__).resolve().parent.parent
    raw_path = project_root / "dataset" / "val_500_raw.json"
    out_path = project_root / "dataset" / "speech_massive_lora_500_val.json"
    
    if not raw_path.exists():
        print(f"❌ Error: {raw_path} not found.")
        sys.exit(1)
        
    print(f"⏳ Reading raw validation split from {raw_path}...")
    with open(raw_path, "r", encoding="utf-8") as f:
        raw_data = json.load(f)
        
    print(f"✅ Loaded {len(raw_data)} raw samples successfully.")
    
    # 2. Generate augmented records using premium Gemini responses
    augmented_data = []
    for item in raw_data:
        item_id = item["id"]
        utt = item["utt"]
        intent = item["intent"]
        scenario = item["scenario"]
        
        response = generate_dynamic_gemini_response(item_id, intent, scenario, utt)
        
        augmented_data.append({
            "id": item_id,
            "utt": utt,
            "intent": intent,
            "scenario": scenario,
            "response": response
        })
        
    # 3. Save augmented data to JSON file
    print(f"💾 Saving premium validation dataset to {out_path}...")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(augmented_data, f, ensure_ascii=False, indent=2)
        
    print(f"🎉 Successfully augmented {len(augmented_data)} validation samples with premium responses!")
    print(f"📁 Output saved to {out_path}")

if __name__ == "__main__":
    main()
